### ISSUE TITLE
this case tested in Inav 7.0.0? INAV 6.1.x still error.

### ISSUE THREAD

**Issue by NoviKurniawan** [iNavFlight/inav#9267] opened 2023-08-30 10:16 UTC
this case tested in Inav 7.0.0? INAV 6.1.x still error.
when is INAV 7.0 released?

_Originally posted by @NoviKurniawan in https://github.com/iNavFlight/inav/issues/9150#issuecomment-1680383853_

**Comment by stronnag** [comment] 2023-08-30 10:57
Duplicate of #9150

**Closed as completed by stronnag** 2023-08-30 10:57 UTC
