### ISSUE TITLE
Manual throttle launch mode

### ISSUE THREAD

**Issue by brassman84** [iNavFlight/inav#4578] opened 2019-04-05 07:06 UTC
## Current Behavior
An alternative launch mode for people who are unsuccessful with the current auto launch or who thinks auto launch is to dangerous.

## Desired Behavior
a mode simular to horizon/angle mode but with the nav_fw_launch_climb_angle active so the plane climbs instead of leveling out, throttle is controlled manualy. Also it could be timed using nav_fw_launch_timeout.

## Who does this impact? Who is this for?
This feature would be for fixed wing only.

**Comment by P-I-Engineer** [comment] 2019-04-10 21:25
make a mix on a switch in your radio for up elevator, now launch with that on and in angle mode.

**Comment by michaelvanderhoek** [comment] 2019-05-02 11:20
agree with PI engineer. I also launch my wing with a switch on elevator.

**Comment by shellixyz** [comment] 2019-06-07 05:30
Duplicate of #3858, closing

**Closed as completed by shellixyz** 2019-06-07 05:30 UTC
Labels: New Feature
