### ISSUE TITLE
EVO "bricked" after SS1 merge

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#1490] opened 2017-03-30 21:39 UTC
My EVO no longer connects via the CLI or configurator after f4fd8d4c7d6631402b07deabb26a8d79da4b0a55

**Comment by digitalentity** [comment] 2017-03-31 00:21
Bug affects not only EVO and is not caused by SS1 merge - fixed in #1491

**Closed as completed** 2017-03-31 00:48 UTC
