### ISSUE TITLE
MSP-over-Crossfire to enable changes to be made via ELRS wifi

### ISSUE THREAD

**Issue by Narnasqueneth** [iNavFlight/inav#8388] opened 2022-09-12 17:04 UTC
## Desired Behavior
Betaflight now allows users to connect to their FCs wirelessly through the wifi feature of certain (many) ELRS receivers. See the 4:00-5:49 of JB's video here https://www.youtube.com/watch?v=cyILQqxPpZI&t=333s 

Desired behaviour is that iNav allows users same functionality

## Suggested Solution
Implement (steal) same/similar code to that which was done for Betaflight to enable this feature

## Who does this impact? Who is this for?
All users who have ELRS receivers capable of wifi

**Comment by MrD-RC** [comment] 2022-09-12 19:09
Duplicate of https://github.com/iNavFlight/inav-configurator/issues/1616

**Closed as completed by MrD-RC** 2022-09-12 19:09 UTC
