### ISSUE TITLE
INAV 5.1.0 did not return to home with normal accuracy

### ISSUE THREAD

**Issue by Torchi** [iNavFlight/inav#8454] opened 2022-10-09 09:59 UTC
Drone was sent to an automatic mission (attached zip of xml)

The automatic mission goes to a place 600m away and comes back, repeats once the going and coming, finally lands home.

This automatic mission was flown one flight .  Then battery changed.  Flown again in a second flight.

While first flight RTH  returned "exactly" (i.e. within a meter or two) to home, second flight returned with maybe 20 meters offset (therefore outside runfield...).

Everything was same in the two missions besides texact take off locations (both were in the runfield but a bit different) and manual take offs.  

The recording of the two missions is attached (BB).

Attached also pictures of the two missions and details showing home area.

[600m.mission.zip](https://github.com/iNavFlight/inav/files/9741257/600m.mission.zip)

[blackbox_log_2022-10-08_114352.TXT](https://github.com/iNavFlight/inav/files/9741258/blackbox_log_2022-10-08_114352.TXT)

![1](https://user-images.githubusercontent.com/18173871/194750046-cbec131e-3f2d-4673-a3c7-8b1e78027001.png)

![2](https://user-images.githubusercontent.com/18173871/194750052-2e22fcc6-6c8a-421d-ad07-493c9444aa20.png)

![1detail](https://user-images.githubusercontent.com/18173871/194750056-44e3f3bd-5140-4163-88a8-ea9bc76286cb.png)

![2detail](https://user-images.githubusercontent.com/18173871/194750064-85153af9-3c04-46bb-8228-8372b58913a0.png)

**Comment by stronnag** [comment] 2022-10-09 10:35
In fact, the second attempt terminates precisely at WP8. 

![Screenshot from 2022-10-09 11-30-58](https://user-images.githubusercontent.com/158229/194752002-62a1f8a5-78ec-4a2d-821b-15b4e9749536.png)

**Comment by stronnag** [comment] 2022-10-09 11:13
It is also the case that at BBL iteration `292032` ( 294.6s), the HOME position is changed in the BBL. 

Do you have a `reset home` switch ? Did you accidentally switch it?

**Comment by Torchi** [comment] 2022-10-09 11:58
I have a switch that makes the drone return home.  I have not touched switches at that time (as far as I am aware of). 
But even in that accidental case, that "return home" switch  is what you mean for 'reset home switch' ?

**Comment by stronnag** [comment] 2022-10-09 12:21
> But even in that accidental case, that "return home" switch is what you mean for 'reset home switch' ?

No. There is also a "HOME RESET" mode.

**Comment by breadoven** [comment] 2022-10-09 12:42
It shouldn't be possible to reset Home in WP or RTH modes even if attempted. It's prevented according to the code. The target position changed as soon as WP8 was reached to within around 2 meters of the WP8 position. Went straight to RTH landing so it must have thought it was Home. Does it show a definite Home Reset flag @stronnag in your tools, can't anything like that in Blackbox Explorer or Decoder ?

**Comment by stronnag** [comment] 2022-10-09 12:50
> Does it show a definite Home Reset flag @stronnag in your tools, can't see anything like that in Blackbox Explorer or Decoder ?

All my stuff depends on `blackbox_decode`. I'm also baffled as to why the home changed (which is clear in the BBL).

**Comment by breadoven** [comment] 2022-10-09 12:50
@Torchi What is your setting for nav_min_rth_distance ? Seems to be 5000 in the dump from https://github.com/iNavFlight/inav/issues/8441 which is much higher than the default of 500. This will cause RTH to land if RTH is initiated when within 50 m of home.

**Comment by stronnag** [comment] 2022-10-09 13:09
We have a winner!

* For flight 1, Home (44.801275 8.762048)    is 53m from WP8 (RTH)
* For flight 2, Home (44.801205 8.762211) is 40m from WP8 (RTH)

Expected behaviour.

**Comment by Torchi** [comment] 2022-10-09 16:14
Congratulations !
I think that if I did it on purpose (to put WP8 in such a critical  position wrt the landing strip) I would never succeed ...

The 5000, non-default, value for nav_min_rth_distance comes probably from some old situation that I do not even remember of.
Actually I do not see now a value for me to use a figure different from  500 so, from now on, I shall revert to  that default.
Thank you.

**Comment by stronnag** [comment] 2022-10-09 17:30
I think we can now close this. Interesting investigation.

**Closed as completed by stronnag** 2022-10-09 17:30 UTC
