### ISSUE TITLE
Throttle telemetry feedback from actual motor output

### ISSUE THREAD

**Issue by wilco1967** [iNavFlight/inav#1878] opened 2017-07-11 16:46 UTC
Feature request. (iNav 1.7.1)

<EDIT> (I mean OSD, not Frsky telemetry...)

Would it be possible to get the actual motor throttle, as sent out to the ESC, shown in the OSD ? 
Right now, the OSD is showing throttle stick position.

When flying in RTH or alt-hold (any mode where throttle is automatically controlled), it would make more sense to show the output to ESC, rather then THR stick position.

Thanks a lot !

**Comment by digitalentity** [comment] 2017-07-13 08:51
Telemetry sends rcCommand[THROTTLE] as a value. It's set by AltHold and it's exactly the value that goes to ESCs.

**Comment by giacomo892** [comment] 2017-07-13 09:43
@digitalentity I think on MWOSD for example you can only show the remote control stick position :) Maybe that's the issue.

**Comment by wilco1967** [comment] 2017-07-13 14:49
Yes, giacomo, that's correct. 

On MWOSD, but also on the build-in OSD (Omnibus F3), it always shows throttle stick position....
I might not have explained that clearly enough earlier. (I wrote telemetry first, before realizing I really meant OSD).

For external MWOSD, it probably a 'feature' in the MWOSD software.  
But for build-in OSD, it is part of iNav software (might have originated from the same code base perhaps ?).
Happens both on the build in and external OSD.

No big deal, but if it's a minor change, perhaps worth 'improving' (at least on the build-in OSD)....

Thanks !

**Comment by fiam** [comment] 2017-09-17 14:05
Since we already have `rcCommand[THROTTLE]` on the telemetry, it seems this would be completely fixed by fixing #2031.

**Comment by fiam** [comment] 2017-09-26 11:36
Closing this as a duplicate of #2031, since that one has some conversation regarding how to implement the feature.

**Closed as completed by fiam** 2017-09-26 11:36 UTC
Labels: Enhancement
