### ISSUE TITLE
Add more steps for AHI & HUD offset

### ISSUE THREAD

**Issue by Zogar89** [iNavFlight/inav#9139] opened 2023-06-21 02:38 UTC
## Current Behavior
With the advent of digital systems, the screen has more resolution up and down. This makes 2 steps insufficient. Personally I prefer to fly with the camera looking down to observe the ground and this function is very useful for me.

## Suggested Solution
Add more steps up and down.

## Who does this impact? Who is this for?
All digital FPV.

## Additional context

![imagen](https://github.com/iNavFlight/inav/assets/11767960/bbbb6b51-1b28-4869-9c65-4c9442c2aed4)

**Comment by MrD-RC** [comment] 2023-06-21 05:51
Closed - Duplicate of https://github.com/iNavFlight/inav-configurator/issues/1787

**Closed as completed** 2023-06-21 05:52 UTC
