### ISSUE TITLE
GPS data delayed several seconds

### ISSUE THREAD

**Issue by FranzAr** [iNavFlight/inav#3970] opened 2018-10-30 07:06 UTC
iNav 2.0
Airbot Omnibus F4 pro V3
Beitian BN-220 GPS

GPS data is delayed up to 10 seconds as you can see in my video. This doesn't happen in every flight but every one and then. If it happens it is during the whole flight.

https://www.youtube.com/watch?v=o8yy23SOid0

I'm not sure if this is an iNav or a hardware issue. Over in the facebook group 1 or 2 other users had similar issues. 

Any hints?

**Comment by digitalentity** [comment] 2018-10-30 07:14
Duplicate of #3908

**Closed as completed by digitalentity** 2018-10-30 07:14 UTC

**Comment by konraddi** [comment] 2018-11-06 08:35
This issue existed since at least August 2017! I was never able to use those two gps modules because of that. Gladly I kept them for more than a year, an tested them this morning with 2.0.1, working properly now without delay, thanks for fixing!! #1896

https://github.com/iNavFlight/inav/issues/1896

**Comment by konraddi** [comment] 2018-11-06 08:46
[
![img-20181105-wa0024](https://user-images.githubusercontent.com/30178550/48052614-c6bf9600-e1a8-11e8-9478-7a538f1ea75d.jpeg)
