### ISSUE TITLE
MAMBAF722 - freeze after 20 seconds

### ISSUE THREAD

**Issue by kolaa** [iNavFlight/inav#5733] opened 2020-05-15 16:11 UTC
## Current Behavior
firmware 2.5.0 RC1

Mamba f722 board freeze after statup

## Steps to Reproduce
1. Flash firmware with full flash erase
2. Connect to USB
3. Freeze after initialization

## Expected behavior
it works

## Suggested solution(s)
fix firmware for this board

## Additional context
no

Diatone MAMBA F722S

**Comment by digitalentity** [comment] 2020-05-15 18:38
Confirmed, investigating

**Comment by digitalentity** [comment] 2020-05-15 19:23
Caused by an edge-case in 6665c7e877fe5451a6d5824c75da54d1e05b916f when mixer is not configured (0 motors), but `ESC_SENSOR` is assigned to a serial port. Fix pending.

**Closed as completed** 2020-06-07 07:25 UTC
Labels: Bugfix
