### ISSUE TITLE
 BLHeliSuite Does not read the settings of the speed controllers via the Omnibusf4v3 flight controller on firmware 2.0.0 rc3

### ISSUE THREAD

**Issue by lavaed** [iNavFlight/inav#3582] opened 2018-07-12 19:31 UTC
### Board and Version
_Board name goes here. If you have a link where you've purchased the board - please include it_
_Version of INAV used goes here_

_Use CLI command `version` and put its output here_

_If it's a custom-compiled firmware please mention this_

### Behavior
* _Describe the problem_
* _Steps needed to reproduce the problem_
* _Expected Results_
* _Actual Results_

_Is this a new feature request?_

#### Blackbox logs/Config (.ZIP) where problem occurs
_Go to CLI, execute `dump` command copy its output to [PasteBin](https://pastebin.com) and provide a link to a paste here.

_Upload a zipped blackbox log (if available)_

**Comment by giacomo892** [comment] 2018-07-12 19:48
Are you sure ESCs are running BLHeli?
Are you powering up the quad with battery before connecting BLHeli Suite?

Try BLHeli - Configurator from chrome app store too.

**Comment by lavaed** [comment] 2018-07-12 22:02
All you described I do. But on firmware 1.9.1 omnibusf4v3 everything works, and when I flash on 2.0.0rc3 nothing works.

**Comment by digitalentity** [comment] 2018-07-26 19:45
@lavaed what ESCs are you using? I'm going to try and reproduce the issue.

**Comment by digitalentity** [comment] 2018-07-29 17:03
@lavaed please update on ESC brand and make?

**Comment by digitalentity** [comment] 2018-08-05 15:58
Can't reproduce. Tested BLHeli_S & BLHeli32 ESCs. Closing.

**Closed as completed by digitalentity** 2018-08-05 15:58 UTC
Labels: Feedback required
