### ISSUE TITLE
Horizon Drift Fixed?

### ISSUE THREAD

**Issue by a6j** [iNavFlight/inav#8145] opened 2022-06-22 05:47 UTC
Hello.
I haven't used INAV for two years. Now I use the Matek F405-wse flight controller on two planes.
I tried INAV 3.0, 4.1 and even release candidate 5.0. And on all versions there is a problem with horizon drift.
I really like the ideology of INAV and I don't want to switch to Ardupilot. I tried to 
reduce the sensitivity of imu_acc_ignore_rate = 7, but this gives only a small result
and does not solve the problem. It is currently impossible to fly on INAV. What are your ideas?

**Comment by MrD-RC** [comment] 2022-06-22 05:58
This is a duplicate of what you posted in https://github.com/iNavFlight/inav/issues/1776. Please keep everything in the one issue.

**Closed as completed** 2022-06-22 05:58 UTC
