### ISSUE TITLE
INAV 5.0 suddenly and had random reset previous configuration to default 

### ISSUE THREAD

**Issue by abimaputra78** [iNavFlight/inav#8320] opened 2022-08-15 10:09 UTC
**PLEASE MAKE SURE YOU READ AND UNDERSTAND THE SOCIAL MEDIA SUPPORT CHANNELS. QUESTIONS ABOUT FLASHING, CONFIGURING, PILOTING MAY BE CLOSED WITHOUT FURTHER INTERACTION.**

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)

**Please double-check that nobody reported the issue before by using search in this bug tracker.**

**PLEASE DELETE THE TEXT ABOVE AFTER READING AND UNDERSTANDING IT**

****

## Current Behavior

Unknown Cause: Inav 5.0 currently had a random cofiguration reset to default. I had my Inav 5.0 reset,  during lipo plug in. That was nothing to do with USB Connection this time.

## Steps to Reproduce

1. Change empty Lipo in the field after several INAV flights. 
2. Plug the charged lipo 
3. Abnormal Long beep after start up.
4. All Previously value in INAV Configuration had  reset and back to default. 

## Expected behavior
 lipo or usb plug should not make any reset act to default to its previous configuration 

## Suggested solution(s)
 would you please fix stability of the firmware not being reset by above issues. 

## Additional context

---

 INAV 5.0.0 release

- FC Board name and vendor: Kakute H7 
- INAV version string: 5.0.0 release

**Comment by MrD-RC** [comment] 2022-08-15 10:37
Duplicate of https://github.com/iNavFlight/inav/issues/7128

**Closed as completed** 2022-08-15 10:38 UTC
