### ISSUE TITLE
Maximum distance from home

### ISSUE THREAD

**Issue by Mansell1994** [iNavFlight/inav#5511] opened 2020-03-18 15:03 UTC
## Current Behavior
In the current version inav relies on other hardware such as the receiver to trigger a fail safe for loss of signal. However many entry level receivers do not have this function, causing many 'fly aways'.

## Desired Behavior
A software solution would be cheap and invaluable to many new flyers who have not invested in more expensive hardware. 

## Suggested Solution
Such solution could be a line of code, 'if distance to home greater than X then activate failsafe'.

## Who does this impact? Who is this for?
For people like me who fly a fixed wing, often in 3d cruise or angle mode, that do not have failsafe built into the receiver certain situations could arise where if signal is lost then the plane will fly away and be lost. If this could be achieved then once the plane has flown past 500 metres for example then the failsafe would be triggered bringing it back into signal range or landing.

I imagine that this would apply to quadcopters too.

**Comment by digitalentity** [comment] 2020-03-19 11:57
Duplicate of #62

**Closed as completed by digitalentity** 2020-03-19 11:57 UTC
