### ISSUE TITLE
Home arrow disappear beyond 1000m from home - Omnibus F4 - iNav 1.7.3 beta

### ISSUE THREAD

**Issue by asteman** [iNavFlight/inav#2186] opened 2017-09-20 19:33 UTC
Hi,

I've noticed that the home pointer arrow disappear when beyond 1000m from home. Only to blink briefly every now and then. When getting back within 1000m from home the arrow stays on permanently.

True for both the standard font and the improved one downloaded from issue 1443.

Bug or feature?

**Comment by fiam** [comment] 2017-09-20 20:43
@asteman It's either a bug or either user error :-). Definitely not working as intended.

Can you post a capture from the DVR with your OSD arrangement? (obscure or delete any potentially identifying information!) I suspect some other element might be overwriting the home arrow. If you can't provide an image, please post a dump and I'll try to replicate the problem on the bench.

**Comment by asteman** [comment] 2017-09-20 21:14
@fiam Here are 2 screen captures:
Beyond 1000m
![image](https://user-images.githubusercontent.com/25367091/30667723-c67892f8-9e58-11e7-85e6-84dfdbd2c541.png)

Within 1000m
![image](https://user-images.githubusercontent.com/25367091/30667794-034db01e-9e59-11e7-903c-9bca356cdb9a.png)

My guess is that the 4th digit overwrites the arrow even though it looks like there are space for it in the second screenshot. If that's the issue, perhaps making it future proof to allow for 5 digits as well ;)

**Comment by digitalentity** [comment] 2017-09-21 04:21
Yes, our `osdFormatDistanceStr` adds an extra space at the end of distance which overwrites the home arrow with this layout.

@asteman is this the default layout of cuzstomized one?

**Comment by asteman** [comment] 2017-09-21 06:06
@digitalentity It's the bold font. But I'm pretty sure this was an issue with the default font as well.

**Comment by fiam** [comment] 2017-09-21 17:22
How about something like this? I've just done the changes to ALT, but DIST would get more or less the same. Different symbols are used as a prefix to indicate the unit: meters and kilometres for metric and feet and thousands of feet for imperial. Not sure which units we would use for DIST in imperial yet. Nice thing is the indicator always uses the same space, adjusting decimals and whitespace as required.

<img width="500" alt="screen shot 2017-09-21 at 17 03 43" src="https://user-images.githubusercontent.com/41529/30709251-85d377d0-9ef9-11e7-85e9-6815f4541448.png">
<img width="518" alt="screen shot 2017-09-21 at 17 00 29" src="https://user-images.githubusercontent.com/41529/30709252-879170cc-9ef9-11e7-9408-9e304a650d81.png">
<img width="507" alt="screen shot 2017-09-21 at 16 59 16" src="https://user-images.githubusercontent.com/41529/30709254-88a519f0-9ef9-11e7-8bb6-636ef748f0d7.png">

**Comment by fiam** [comment] 2017-10-03 15:37
Fixed in #2200

**Closed as completed by fiam** 2017-10-03 15:37 UTC
Labels: Bugfix
