### ISSUE TITLE
Detecting MS5611 baro falis on SPRacingF3 (Acro) board 

### ISSUE THREAD

**Issue by Xe54** [iNavFlight/inav#774] opened 2016-11-08 22:50 UTC
Powering the board causes an I2C error with the current version 1.3 and the baro is not activated in the hardware bar. After rebooting the board (switching to cli and back) the baro is detected and works properly. Known workaround is to explicitly set baro_hardware = 3. Here is the status before workaround:

# status
System Uptime: 94 seconds, Voltage: 156 * 0.1V (4S battery - OK), System load: 0.10
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=HMC5883
Cycle Time: 1009, I2C Errors: 2, config size: 1988

And here is the status after:

# status
System Uptime: 22 seconds, Voltage: 156 * 0.1V (4S battery - OK), System load: 0.10
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=HMC5883
Cycle Time: 1009, I2C Errors: 1, config size: 1988

**Comment by Xe54** [comment] 2016-11-08 22:53
My dump:

# dump

# version

# INAV/SPRACINGF3 1.3.0 Nov  2 2016 / 11:15:52 (479d607)

# pflags

# Persistent config flags: 0x00000001

# dump master

# mixer

mixer QUADX
mmix reset
smix reset

# feature

feature -RX_PPM
feature -VBAT
feature -UNUSED_1
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -UNUSED_2
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature VBAT
feature RX_SERIAL
feature MOTOR_STOP
feature SERVO_TILT
feature SOFTSERIAL
feature GPS
feature FAILSAFE
feature TELEMETRY
feature CURRENT_METER
feature BLACKBOX

# beeper

beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB

# map

map TAER1234

# serial

serial 0 64 115200 38400 0 115200
serial 1 2 115200 115200 0 115200
serial 2 32 115200 38400 0 115200
serial 30 1 57600 38400 0 115200
serial 31 256 115200 38400 57600 115200

# led

led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color

color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color

mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

set looptime = 2000
set i2c_overclock = OFF
set gyro_sync = ON
set gyro_sync_denom = 1
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1080
set max_throttle = 1860
set min_command = 1000
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 1000
set motor_pwm_rate = 2000
set motor_pwm_protocol = ONESHOT125
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 10
set small_angle = 25
set reboot_character = 82
set gps_provider = UBLOX
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_4G
set gps_auto_config = ON
set gps_auto_baud = ON
set inav_auto_mag_decl = ON
set inav_accz_unarmedcal = ON
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_gps_min_sats = 6
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = ON
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_max_speed = 300
set nav_max_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 500
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_tail_first = OFF
set nav_rth_alt_mode = AT_LEAST
set nav_rth_altitude = 2000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1480
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_roll2pitch = 75
set nav_fw_loiter_radius = 5000
set serialrx_provider = SBUS
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = ON
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 285
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = CW270FLIP
set align_board_roll = -2
set align_board_pitch = -6
set align_board_yaw = 0
set gyro_lpf = 42HZ
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set pos_hold_deadband = 20
set alt_hold_deadband = 10
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = RTH
set rx_min_usec = 885
set rx_max_usec = 2115
set acc_hardware = 0
set baro_use_median_filter = ON
set baro_hardware = 3
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SPIFLASH
set magzero_x = 12
set magzero_y = -126
set magzero_z = -117
set acczero_x = 32
set acczero_y = 17
set acczero_z = 61
set ledstrip_visual_beeper = OFF
set accgain_x = 4071
set accgain_y = 4090
set accgain_z = 4046

# rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 h
rxfail 4 s 1100
rxfail 5 s 1500
rxfail 6 s 1500
rxfail 7 h
rxfail 8 s 1100
rxfail 9 s 1900
rxfail 10 s 1500
rxfail 11 s 1500
rxfail 12 s 1500
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile

profile 0

# aux

aux 0 1 4 900 1300
aux 1 2 4 1300 1700
aux 2 19 5 1300 2100
aux 3 22 7 1700 2100
aux 4 5 7 900 1300
aux 5 3 5 1300 2100
aux 6 9 5 1700 2100
aux 7 8 0 1500 2100
aux 8 18 6 1700 2100
aux 9 20 6 900 1300
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo

servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set nav_alt_p = 50
set nav_alt_i = 0
set nav_alt_d = 0
set nav_vel_p = 100
set nav_vel_i = 50
set nav_vel_d = 10
set nav_pos_p = 65
set nav_pos_i = 120
set nav_pos_d = 10
set nav_posr_p = 180
set nav_posr_i = 15
set nav_posr_d = 100
set nav_navr_p = 10
set nav_navr_i = 5
set nav_navr_d = 8
set deadband = 5
set yaw_deadband = 5
set throttle_tilt_comp_str = 0
set flaperon_throw_offset = 250
set flaperon_throw_inverted = OFF
set gimbal_mode = NORMAL
set fw_iterm_throw_limit = 165
set mode_range_logic_operator = OR
set default_rate_profile = 0
set mag_declination = 230
set mag_hold_rate_limit = 90
set p_pitch = 60
set i_pitch = 10
set d_pitch = 15
set p_roll = 40
set i_roll = 10
set d_roll = 15
set p_yaw = 65
set i_yaw = 10
set d_yaw = 15
set p_level = 20
set i_level = 15
set d_level = 75
set max_angle_inclination_rll = 500
set max_angle_inclination_pit = 500
set gyro_soft_lpf_hz = 60
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000

# dump rates

# rateprofile

rateprofile 0

set rc_expo = 80
set rc_yaw_expo = 40
set thr_mid = 45
set thr_expo = 0
set roll_rate = 20
set pitch_rate = 20
set yaw_rate = 20
set tpa_rate = 0
set tpa_breakpoint = 1500

**Comment by digitalentity** [comment] 2016-11-21 10:21
@Xe54 can you verify with INAV 1.4-RC1?

**Comment by DzikuVx** [comment] 2016-11-21 10:23
I can test all my baros today with SPRF3

pon., 21.11.2016 o 11:21 użytkownik Konstantin Sharlaimov <
notifications@github.com> napisał:

**Comment by Xe54** [comment] 2016-11-23 12:41
I will give it a try this weekend.

**Comment by DzikuVx** [comment] 2016-11-24 19:03
Just testes SPRF3 Acro on INAV 1.4RC1 with all my baros: MS5611, BMP085/180, BMP280

In all cases baros were detected without any problems. Closing. @Xe54  if problem will reappear, reopen this ticket

**Closed as completed by DzikuVx** 2016-11-24 19:03 UTC
Labels: Feedback required

**Comment by Xe54** [comment] 2016-11-26 17:16
Sorry guys I don't know if i'm doing something wrong, but it got worse. Now i'm getting four I2C errors more. My guess is, the problem is still there, but due to this bugfix: "Fixes for sensor detection, now INAV will retry sensor detection up to 5 times before reporting it missing." it is displayed five time now. Setting baro_hardware to 3 still help. Other than before is the behavior of the baro. It is displayed from the beginning in the hardware bar and seems to work (i couldn't perform a flight test yet).

The status below show the errors before and after setting baro_hardware to 3:

# status
System Uptime: 509 seconds, Voltage: 163 * 0.1V (4S battery - OK), System load: 0.09
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=HMC5883
Cycle Time: 1012, I2C Errors: 6, config size: 2024

# status
System Uptime: 212 seconds, Voltage: 163 * 0.1V (4S battery - OK), System load: 0.09
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611, MAG=HMC5883
Cycle Time: 1005, I2C Errors: 1, config size: 2024

**Comment by stronnag** [comment] 2016-11-26 17:22
The difference of 5 is due to 5 failed probes for BMP085/BMP180 with baro_hardware=0 and is entirely to be expected. Explicitly setting baro and mag hardware is encouraged for 1.4.

So it has not got worst, it is working as designed.

From both examples it appears that the baro is detected.

I'm at  a loss to see what is the problem; it appears the baro is detected, and you state it also works.

**Comment by Xe54** [comment] 2016-11-26 17:41
@stronnag I doubt it is the desired behavior of the hardware auto detecting loop. It is not very user friendly if each piece of hardware produces tons of errors at initialization and provides the user to seek the source of those errors. But if it so, then I would suggest to completely disable auto detecting and prompt the user to enable hardware manually.

**Comment by stronnag** [comment] 2016-11-26 17:48
Actually it is the intention, however sub-optimal this may be. The affect of user confusion was predicted at the time of commit. Thank you for confirming that prediction. 

See the final comments in https://github.com/iNavFlight/inav/pull/801#issuecomment-261764676 and https://github.com/iNavFlight/inav/pull/809#issuecomment-261895253
