### ISSUE TITLE
Building under Windows 10 WSL fails

### ISSUE THREAD

**Issue by Scavanger** [iNavFlight/inav#6238] opened 2020-10-25 10:37 UTC
I get syntax errors in build.make files when I build iNav under WSL:
`Built target MATEKF411SE.elf
/bin/sh: 1: Syntax error: "(" unexpected
make[3]: *** [src/main/target/MATEKF411SE/CMakeFiles/MATEKF411SE.dir/build.make:57: src/main/target/MATEKF411SE/CMakeFiles/MATEKF411SE] Error 2
make[2]: *** [CMakeFiles/Makefile2:32144: src/main/target/MATEKF411SE/CMakeFiles/MATEKF411SE.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:32151: src/main/target/MATEKF411SE/CMakeFiles/MATEKF411SE.dir/rule] Error 2
make: *** [Makefile:13131: MATEKF411SE] Error 2`

I found out that the complete Windows environment variable PATH is appended here (is that necessary?), and its not proper escaped:
Example: 
`c/Program\ Files\ (x86)/..` 
Whitespace is escaped, braces not, so make runs into syntax errors.
After adding the escape strings by hand, compilation runs fine.

**Comment by stronnag** [comment] 2020-10-25 11:00
Duplicate of #6146, already addressed in build documentation.

**Closed as completed** 2020-11-05 07:47 UTC
Labels: Bugfix
