### ISSUE TITLE
DSHOT can not be configured for SPEEDYBEEF405V3

### ISSUE THREAD

**Issue by xabc1** [iNavFlight/inav#8919] opened 2023-03-26 12:59 UTC
It always return to MULTISHOT after saving it. I'm using Inav 6.0.

**Comment by xabc1** [comment] 2023-03-26 13:03
went back to 5.1 but still the same - DSHOT can't be configured on this FC

**Comment by stronnag** [comment] 2023-03-26 13:04
Duplicate of #8817, #8910

**Closed as completed by stronnag** 2023-03-26 13:04 UTC

**Comment by xabc1** [comment] 2023-04-30 15:07
Just an update. DSHOT works in betaflight for SPEEDYBEEF405V3. Even works with bidirectional.
