### ISSUE TITLE
Scrolling Side Bar movement is inverted

### ISSUE THREAD

**Issue by malinhiles** [iNavFlight/inav#9519] opened 2023-11-29 06:58 UTC
## Current Behavior
The Altitude side of the scrolling sidebar moves opposite of how it should. When losing altitude, the scroll bar "scrolls down", and when gaining altitude, it "scrolls up". 
![altitude wrong](https://github.com/iNavFlight/inav/assets/93371446/10d8c98f-dc8c-4e2d-a1dc-d147108b8794)

## Expected behavior
The scrolling behavior should be inverted for the altitude scroll bar. It should "Scroll Down" as the aircraft climbs, like almost all aircraft flight computer displays. Here's a Garmin Autopilot for example: https://youtu.be/YSxWhfr18h4?si=4WRS-yYz3o_iLETO&t=440

## Suggested solution(s)
I'm not a code buff, but i think it would be a pretty quick fix, probably just flip the sign of some integer in the code for that element.

**Comment by MrD-RC** [comment] 2023-11-29 08:37
Duplicate of https://github.com/iNavFlight/inav/issues/9195

**Closed as not planned by MrD-RC** 2023-11-29 08:37 UTC
