### ISSUE TITLE
AHI/Crosshair offset to the right 2.2.1

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav#5010] opened 2019-08-14 02:13 UTC
I have tried it with 2 different FC's and 3 different camera's in PAL. And the result is the same.
I went looking through the CLI and could only found  `osd_horizon_offset`. Which moved it up and down, not left or right.
Is there a command I have missed?

The preview is correct.
![Capture 1](https://user-images.githubusercontent.com/47995726/62988984-a801d480-be89-11e9-879d-310316f73947.png)

While the OSD has the cross hair offset to the right by one character.
![PICT0006](https://user-images.githubusercontent.com/47995726/62988947-7ab52680-be89-11e9-81da-cac88d72c2d0.jpg)

**Comment by FinalFrag** [comment] 2019-08-14 12:10
This seems like duplicate of #4911

**Comment by digitalentity** [comment] 2019-08-14 19:29
Duplicate of #4911

**Closed as completed by digitalentity** 2019-08-14 19:29 UTC
Labels: Bugfix
