### ISSUE TITLE
Incorrect Longitude displayed in DJI FPV goggles V2

### ISSUE THREAD

**Issue by kelleysislander** [iNavFlight/inav#6770] opened 2021-04-01 15:57 UTC
I just got the V2 goggles and the longitude is incorrectly displayed, but it does follow waypoints fine, so the issue is just the displayed value. Please see the attached images. The 332.xxx longitude is from the V2 goggles, the correct longitude 96.xxx is from the V1 goggles
****
![v2_goggles_incorrect_longitude](https://user-images.githubusercontent.com/552098/113321043-d0497b80-92d8-11eb-82a4-5729c6aa1537.jpg)
![v2_goggles_in_the_field](https://user-images.githubusercontent.com/552098/113321132-e8b99600-92d8-11eb-8a5d-48d3123c853d.jpg)
![v1_goggles_correct_longitude](https://user-images.githubusercontent.com/552098/113321147-ec4d1d00-92d8-11eb-863b-a7b341df0e2f.jpg)

## Steps to Reproduce

1.  Link an Inav 2.6.0 quad with OSD and GPS to the newer DJI FPV goggles v2

## Expected behavior
The longitude should be correct
## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by DzikuVx** [comment] 2021-04-09 07:09
Duplicate of #6791

**Closed as completed by DzikuVx** 2021-04-09 07:09 UTC
