### ISSUE TITLE
motor 6 does not run on Hexa-X with Matek F722

### ISSUE THREAD

**Issue by imrj** [iNavFlight/inav#2909] opened 2018-03-12 12:55 UTC
setup a hexa-x on Inav 1.9.0 with Matek F722 target, but Inav does not run motor 6, neither in motor test mode or with arm mode....this is not a hardware issue as this same exact hexa-x config operates all
[INAV_cli_MatekF722.txt](https://github.com/iNavFlight/inav/files/1802787/INAV_cli_MatekF722.txt)
 motors on BF3.3....this is only happening with Inav.
config file attached

**Comment by digitalentity** [comment] 2018-03-12 12:56
Duplicate of https://github.com/iNavFlight/inav/issues/2872. Fixed

**Closed as completed by digitalentity** 2018-03-12 12:56 UTC
