### ISSUE TITLE
Add support for mission flight without rc link

### ISSUE THREAD

**Issue by JonnyFPV** [iNavFlight/inav#2972] opened 2018-03-26 20:17 UTC
Hello, 

It would be nice if it is possible to let planed mission go if you lose rc link. 

And if you hit failsave manually or rth mode the plane or copter will enter this mode if it get rc link back if you trigger any of this modes.

**Comment by driesvandenbroecke** [comment] 2018-03-26 21:43
yes  if you have your failsafe linked to the failsafe switch on Inav, then it shouldn't be too hard to do it. Have the option in mission control to continue the mission when no radio link or go straight rtl.

**Comment by shellixyz** [comment] 2018-03-28 13:06
Duplicate of #977, #2340 and #770

**Comment by shellixyz** [comment] 2019-06-07 05:27
Available in 2.2, closing

**Closed as completed by shellixyz** 2019-06-07 05:27 UTC
Labels: New Feature
