### ISSUE TITLE
iNav 4.1 configurator will not connect when using MATEKSYS H743-WING version 0 and a usb card is inserted

### ISSUE THREAD

**Issue by cd933500** [iNavFlight/inav#8025] opened 2022-05-10 23:06 UTC
I have a MATEKSYS H743-Wing original version and when I upgraded to iNav Configurator 4.1, it would not connect. I originally had a 16G micro card and it would not connect then I install a 8G micro card and it still does not connect. It will connect when no card is inserted or you install a very small card of 256Mg.  The problem does not exists on the older version of iNav (3.02).

**Comment by DzikuVx** [comment] 2022-05-12 07:32
Duplicate of #7759 
In general, use different SD or leave SD card inserted and FC so it can initiate the file system

**Closed as completed by DzikuVx** 2022-05-12 07:32 UTC
