### ISSUE TITLE
Set waypoints on the fly

### ISSUE THREAD

**Issue by gazeddy** [iNavFlight/inav#6934] opened 2021-05-08 00:09 UTC
## Current Behavior
Current mission waypoints have to be preplanned

## Desired Behavior
Id like the ability to set missions on the fly. My current build is a bait boat and would like to be store my "drop" locations so i can return to them easily 

## Who does this impact? Who is this for?
Mainly for rover users however im sure aircraft would benefit. Im aware of several rc fishing boat builders who would like this feature.

## Additional context
The current mission planner system is fine for situations where pre planning is possible. But fishing spots change by the hour so what worked yesterday isnt guaranteed to work today. My idea is to use an rc channel (3pos switch) to store a waypoint,rth and return to waypoint. Carrying a laptop to a fishing lake isnt a great idea imo and connecting via usb to write missions is often difficult or impossible. Ive had very limited success using bluetooth to connect to an fc using a uart and msp protocol

**Comment by b14ckyy** [comment] 2021-05-11 06:55
Duplicate of #4663
You can comment there to push it up.

**Closed as completed** 2021-05-11 09:06 UTC
