### ISSUE TITLE
QuadX 1 Servo setup on Aux channel (for manual tilt) 

### ISSUE THREAD

**Issue by Jock384** [iNavFlight/inav#2024] opened 2017-08-21 21:40 UTC
Hi guys, i built a 250 size quad (SPF3acro, rcsplit, fpv setup) and now im in the process of building a 500 size quad. I got My new Spf3 (deluxe) a couple of days ago and since i want to try to use a GPS so i've flashed the FC with iNav (1.7.2). Since im relatively new to the whole iNav gui/interface, syre i've been using CleanFlight a while bit Still there seem to be some differencies. I tried connecting a 9g sg90 Servo for manual tilt to pwm pin 5 on FC (while using ch_forwarding) in CleanFlight. I got the Servo to work om Aux 5 using channel forwarding but the Servo just jitters and wont turn. I'm just wondering what the easiest way to setup a standard QuadX setup with 1 Servo preferably on Aux ch 5. I can't seem to find any info regarding this matter, or im just too annoyed or stupid atm. I just can't seem to find the cli commands for channel forwarding in inav anywhere :P I would be deeply grateful for any help :) best regards /Jocke

**Comment by digitalentity** [comment] 2017-08-22 00:06
Duplicate of #2022

**Closed as completed by digitalentity** 2017-08-22 00:06 UTC
