### ISSUE TITLE
Add blackbox fields selection

### ISSUE THREAD

**Issue by akbarfoto** [iNavFlight/inav#7347] opened 2021-08-14 10:16 UTC
## Current Behavior

No selection for turning off fields of blackbox such as GPS, Motors, Acc, Gyro, RSSI, and others. 
## Desired Behavior

To be able to select which parameter that is recorded to integrated flash so that it is smaller in size but still maintain the need for high logging rate
## Suggested Solution

Mostly the idea are from betaflight here >> https://github.com/betaflight/betaflight/pull/9726
Adds the ability to select the recorded fields in the blackbox logging. The selection is made using a 32 bit variable organized as in the table

12-31 11 10 9 8 7 6 5 4 3 2 1 0
Unused GPS Motors (and tricopter servo) Debug Acc Gyro RSSI Altitude (Baro and Rangefinder) Magnetometer Battery (Vbat and current) Setpoint RC commands PIDs

## Who does this impact? Who is this for?

This can be useful in:

- For me, I like to use it for GyroFlow stable footage aplication as it only need Gyro data, so can be use for longer flight times, or multiple flights without the need to extract the data. 
- Integrated flash, as they are usually small in size, so this can help reducing the file size, so longer logs
- Serial logging devices, to help reducing the data rate, so maybe dropouts in old logging devices and/or cheap/old sd cards (can be really useful on whoops and micros)
- (Integrated sdcard, maybe reduce some dropouts due to slow sd cards?) [edit] - reduce cpu usage at higher logging rates

Example usage: I want to finely tune my gyro noise, but i want an higher logging rate/i have little space in the integrated flash/i have a crappy sdcard, i can then select only gyro and rccommands logging
I want to do long range and record only rccommands, battery, altitude and gps for a long time (omitting like pids, gyro and others)

## Additional context

credit to the author >>  fgiudice98

**Comment by avsaase** [comment] 2021-08-14 10:57
duplicate of https://github.com/iNavFlight/inav/issues/6597.

**Closed as completed by avsaase** 2021-08-14 10:57 UTC
