### ISSUE TITLE
2.6.0-RC2 no control during launch "finishing"

### ISSUE THREAD

**Issue by shellixyz** [iNavFlight/inav#6314] opened 2020-11-18 21:15 UTC
## Current Behavior

No control during launch "finishing"

See demo, no control from second 10 to 13:
https://www.youtube.com/watch?v=Ia97rpahRNU

## Desired Behavior

Control should be given back to the user as soon as the sticks are wiggled

**Comment by avsaase** [comment] 2020-11-18 21:47
I noticed this too today. On my first launch I also noticed another problem: the airplane pitched up 90 degrees when auto launch was finishing, but I had to wait until it completely finished before I could correct. I was not able to reproduce this on following launches so I can't completely rule out pilot error, though.

**Comment by digitalentity** [comment] 2020-11-19 07:44
Confirmed. Investigating.

**Comment by dragnea** [comment] 2020-11-19 07:57
@shellixyz I added a fix for this

**Closed as completed** 2020-11-19 08:09 UTC
Labels: Bugfix
