### ISSUE TITLE
fixed wing - dive at waypoints if target altitude is not reached

### ISSUE THREAD

**Issue by RomanLut** [iNavFlight/inav#9026] opened 2023-05-02 12:02 UTC
## Current Behavior

If target altitude is not reached at the waypoint, navigation produces dangerous dive, with down pitch and minimum navigation throttle.

If mission is started at the taget altitude, then behaviour is ok.

## Steps to Reproduce
1. Setup mission at very high altitude
2. Start mission below waypoint 1

## Expected behavior
Navigation should gain altitude contantly

## Demo

Mission is setup at 900m, with navigation throttle override enable, and throttle at 100% (where this effect is even more dramatic).

https://user-images.githubusercontent.com/11955117/235655648-89f3a94b-57c7-486b-9b3f-4599aec77a6a.mp4

If mission is started at target altitude ( 900m), behaviour is ok:

https://user-images.githubusercontent.com/11955117/235656469-fbd2d90b-5998-4166-a24e-25a6aa80b3ef.mp4

In the real flight, mission was set  to 300m altitude and flight was started at 30m altitude. Plane has climb ratio about 1.5m/s. Plane crashed at the last RTH waypoint

https://user-images.githubusercontent.com/11955117/235660080-2388e410-5366-46b7-95d1-2f8697c2afbd.mp4

Unfortunatelly I do not have blackbox (only FPV recording with OSD and onboard HD), but problem can be easily reproduced in HITL.

Affected versions: 6.0 release and current master.

[INAV_6.0.0_cli_FPV_SURFWING_dive-mission.txt](https://github.com/iNavFlight/inav/files/11372663/INAV_6.0.0_cli_FPV_SURFWING_dive-mission.txt)

**Comment by RomanLut** [comment] 2023-05-02 12:32
Attached blackbox log, generated in HITL.

[blackbox_log_2023-05-02_143047.TXT](https://github.com/iNavFlight/inav/files/11373056/blackbox_log_2023-05-02_143047.TXT)

**Comment by Jetrell** [comment] 2023-05-02 23:34
There was this issue, that seems to be related.. #8882 . A fix was added to 6.1. #8896

**Comment by breadoven** [comment] 2023-05-03 09:39
This does look like the issue hopefully fixed by #8896. I'm surprised nobody noticed it before because it's probably been there for some time.

**Comment by breadoven** [comment] 2023-05-03 10:46
Actually looking at the log it's the same issue as #8882 but working in a different way due to the way target altitude is set during each WP leg and the affect this has in the altitude PID P and I values. It would need a different fix, probably resetting the PIDs at the start of each leg. Flagging as a bug for now.

**Comment by RomanLut** [comment] 2023-05-03 11:28
Not fixed by https://github.com/iNavFlight/inav/pull/8896.

Attached is a video from 6.0 + #8896, 
nav_fw_pos_z_p=35 
nav_fw_pos_z_p = 5
nav_fw_pos_z_d = 10
with POSZ PID controller outputs on OSD.

Note that real flight video above is done on firmware from master branch (later than 6.1 release)


https://user-images.githubusercontent.com/11955117/235903308-5d8e47c3-07a1-4081-b214-71fd1ca73f86.mp4

**Comment by shota3527** [comment] 2023-08-06 17:46
I dont think this is a bug, this issue is just caused by anti-windup in nav pid controller, iterm turns the opposite when the controller is saturated

**Comment by b14ckyy** [comment] 2024-03-21 16:17
Was this fixed with #9224?

**Closed as completed** 2024-03-24 14:08 UTC
Labels: Bugfix
