### ISSUE TITLE
iNav firmware not working on MATEK F722-STD

### ISSUE THREAD

**Issue by biocage** [iNavFlight/inav#4809] opened 2019-06-09 19:08 UTC
## Current Behavior
After flashing stable firmware 2.1.0, FC boots to a solid red LED, and Configurator is unable to connect. Serial port is present on host PC, but no traffic. Recovery requires powering the FC while the Boot button is held down, and then flashing either a current unstable build, or a working Betaflight build.

## Steps to Reproduce
Keep defaults, including "Show unstable releases" unselected, and then select the latest stable release, which as of 9 June 2019, is 2.1.0, from 25 February 2019). 

Flash iNav onto MATEK F722-STD using iNav Configurator 2.2.0RC2 (or RC1).

## Workaround
Select "Show unstable releases" and then install a newer build (2.2.0RC2 is functional).

**Comment by digitalentity** [comment] 2019-06-09 19:30
Can't reproduce.

Board: MATEKF722-STD
Firmware: MATEKF722
Version: 2.2.0 RC2

![image](https://user-images.githubusercontent.com/11059099/59163182-b0423a00-8afd-11e9-8bd8-6ef4fd153d46.png)

Double-check that you are flashing `MATEKF722` firmware, not the `MATEKF722SE` which is for MATEKF722-WING board.

**Comment by stronnag** [comment] 2019-06-09 19:32
and you flash with 'full chip erase'

**Comment by biocage** [comment] 2019-06-09 19:50
Yup, I did - on both counts.

@digitalentity  It looks like you are using different firmware than the latest "stable". Can you confirm that?

**Comment by digitalentity** [comment] 2019-06-09 19:55
@biocage 2.2.0-RC2 from the repository (releases)

**Comment by biocage** [comment] 2019-06-09 20:07
@digitalentity Ok, that's the same Configurator I'm using, but I saw the second line in your screenshot also says 2.2.0, and the firmware Configurator is offering me is 2.1.0 if I'm on the default stable channel. 

I poked "Show unstable releases" and flashed the unstable version you are using, and it does work. I'm going to update the text of this ticket to reflect the actual issue.

**Comment by digitalentity** [comment] 2019-06-09 21:56
Since the issue is fixed in 2.2.0, I'm closing the ticket.

**Closed as completed by digitalentity** 2019-06-09 21:56 UTC
Labels: Support
