### ISSUE TITLE
Use Low VTX Power While Disarmed - not working in 2.5.0

### ISSUE THREAD

**Issue by namirda** [iNavFlight/inav#5842] opened 2020-06-11 02:38 UTC
## Current Behavior
When arming the craft, the VTX Power as displayed in the OSD remains at 1 instead of increasing to preset value.

## Steps to Reproduce
1) Enable display of "Video Tx Power Level" in the OSD
2) Set VTX Power Level to something greater than 1 in the Configuration tab
3) Set "Use Low Power While Craft is disarmed" to always
4) Confirm that OSD shows 1 for power level while disarmed 
5) Note that OSD does not show a higher power level after arming

## Expected behavior
OSD display of VTX power level should increase when armed. This worked properly in V2.4

## Additional context
I believe that the VTX power does actually increase after arming.  This error is probably only a problem with the OSD display of the power level. 

# version
# INAV/MAMBAF722 2.5.0 Jun 11 2020 / 13:51:33 (694767938)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by digitalentity** [comment] 2020-06-11 06:34
Duplicate of #5731, fixed by #5823

**Closed as completed by digitalentity** 2020-06-11 06:34 UTC
Labels: Bugfix
