### ISSUE TITLE
Turtle Mode

### ISSUE THREAD

**Issue by chrisman92** [iNavFlight/inav#5870] opened 2020-06-22 01:33 UTC
## Current Behavior
No “Flip over after crash mode” if quad lands upside down

## Desired Behavior
Allow turtle mode mode

## Suggested Solution
Copy Betaflight configuration

## Who does this impact? Who is this for?
Anyone running inav that flips their quad over accidentally

## Additional context
Although primarily tailored to “freestyle pilots, even if flying cinematically and you accidentally hit a tree and flip over (yes this has happened to me), this would be extremely handy.

**Comment by digitalentity** [comment] 2020-06-22 06:50
Duplicate of #5126

**Closed as completed by digitalentity** 2020-06-22 06:50 UTC
Labels: New Feature
