### ISSUE TITLE
Inav 3.0.0: Matek H743 target is not usable

### ISSUE THREAD

**Issue by kolaa** [iNavFlight/inav#7038] opened 2021-05-29 12:26 UTC
****

## Current Behavior

Matek H743 target is not usable

## Steps to Reproduce
1. Build taget
2. Upload to board

Finally: Baro not working, GPS on Uart3 not working, dshot not working

**Comment by stronnag** [comment] 2021-05-29 13:22
Duplicate of #6371 
Closing as unhelpful.

**Closed as completed by stronnag** 2021-05-29 13:22 UTC
