### ISSUE TITLE
Feature Request: GPS Output on spare UART

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav#5143] opened 2019-10-15 21:44 UTC
## Current Behavior
Not Available

## Desired Behavior
The ability to mirror the input from the GPS onto a spare usart (or softserial) so that we can have an NMEA or UBX output to something such as an MFD telefly module. That way we don't need to have 2 GPS receivers or tee off (with possible buffer and/or level issues on the receive line) if we wish to run a secondary module for an antenna tracker or even something like a raspberry pi zero for camera control of a second mapping camer that way we can embed the gps data into the EXIF for the photos

## Suggested Solution
The ability to use a spare uart or a softserial for gps output.

## Who does this impact? Who is this for?
This can benefit all users especially us users that like mapping with a secondary computer and also those who use something like an MFD antenna tracker which requires a separate module with a separate gps input to embed gps data into the VBI section of the video frame. 

This should be relatively simple as the gps input is already there it should also send all gps data to the mirror port irrespective if there's enough satellites etc. The telefly module can understand both NMEA and UBX data and it only needs to be "receive only" (ie from FC to module) there is no need to be able to "talk" to the GPS.

**Comment by wx4cb** [comment] 2019-10-15 21:58
here's a link to the module manual: http://www.myflydream.com/inc/lib/download/download.php?DId=60

**Comment by rrk1** [comment] 2019-10-16 02:19
IMHO, making a simple 'ghetto' buffer is so trivial that it does not worth wasting dev's precious time. Most of a time a single npn transistor as emitter follower + about 5.1K load resistor will do okay.
Also, don't think you are allowed to do anything with the processor output :) Shorting it or injecting significant noise into it can do bad things, too, potentially crashing the aircraft.

**Comment by wx4cb** [comment] 2019-10-16 15:31
@rrk1 not sure what you mean by the "processor output" ? Im talking about using a spare uart TX pin to have a "tx only" mirror of the gps data so nothing would be going into the RX pin i dont know how you thinl you could "screw up" the data and crash the aircraft. Having a "ghetto" buffer could actually do that

As far as the buffer goes, i know its trivial, but imho, using for example, the f722 wing like i do, has more than enough uarts to do it and that way you dont have to do anything "ghetto" and everything is at the right levels etc.

**Comment by wx4cb** [comment] 2019-10-18 12:31
So just tested "teeing" the gps off and all i get is gps failure every couple of seconds. I really need this, but not sure how to code it

**Comment by tigert** [comment] 2019-10-28 07:55
There is an issue about implementing NMEA or UBLOX as telemetry: #4693  - as telemetry framework is where this belongs to.

While the above is not yet supported, many projects like antenna trackers use LTM, MavLink or MSP protocol. 

If you want to connect to an on-board Arduino, I think one of those telemetry protocols make more sense, because then you get more data than just location - for example whether your drone is armed, might be useful information.

**Comment by tigert** [comment] 2019-10-28 08:14
@wx4cb just out of curiosity, what GPS is this? 

While looking at the nmea telemetry issue, I found #4688 where someone had repeated gps failures that prevented a tracking device from working. The root cause was INAV expected faster position updates from the older NMEA GPS which resulted in INAV repeatedly reinitializing the GPS connection, and while this "worked" as far as INAV being more or less aware of its position, a tracker device connected to the same wires got confused by the repeatedly reinitialized GPS connection.

Could this be why you have issues too?

**Comment by digitalentity** [comment] 2019-10-28 18:49
Closing as a duplicate of #4693

**Closed as completed by digitalentity** 2019-10-28 18:49 UTC
Labels: New Feature
