### ISSUE TITLE
Feature request: Resource remapping as in BF

### ISSUE THREAD

**Issue by vinicentus** [iNavFlight/inav#1715] opened 2017-05-23 05:15 UTC
How easy would it be to just port over the code for resource remapping from BF? Would this break something or should we give it a try? I kind of need this to max out the capabilities of my FC (Omnibus F4 pro)...

**Comment by digitalentity** [comment] 2017-05-23 05:41
Duplicate of https://github.com/iNavFlight/inav/issues/1145

Also see my last comment in the thread https://github.com/iNavFlight/inav/issues/1145#issuecomment-275632775

**Closed as completed by digitalentity** 2017-05-23 05:41 UTC
