### ISSUE TITLE
Beginner mode

### ISSUE THREAD

**Issue by welon68** [iNavFlight/inav#2167] opened 2017-09-17 15:13 UTC
Hello. I am very interested in the project "Inav" but I'm a weak pilot. Is it possible to design a "**Beginner mode**"? I imagine it as flying in a virtual cylinder, a cylinder of a certain diameter or radius and a corresponding height. These parameters were to be set in the program INAV. Copter would not run away :-)
Best wishes 
welon68

**Comment by digitalentity** [comment] 2017-09-18 01:46
Duplicate of #62

**Closed** 2020-12-11 13:22 UTC
