### ISSUE TITLE
Release hotfix 2.6.1

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#6585] opened 2021-02-08 16:30 UTC
We have some small fixes in `master` worth merging into a hotfix branch. Please nominate PRs to cherry-pick.

Let's aim for `2.6.1` by February 21st.

**Comment by digitalentity** [comment] 2021-02-08 16:30
Baro median filtering - #6584

**Comment by stronnag** [comment] 2021-02-08 16:37
#6418 please

**Comment by DzikuVx** [comment] 2021-02-08 16:42
#6320 with #6327 and #6462

**Comment by rts18** [comment] 2021-02-09 08:12
@digitalentity Was your invitation for anyone? I'd find this #6499 and this #6477 useful early releases.

**Comment by Pairan** [comment] 2021-02-09 09:24
I would like #6459 to enter the hotfix

**Comment by MrD-RC** [comment] 2021-02-09 15:20
#6581 #6499 #6333 #6361

**Comment by breadoven** [comment] 2021-02-11 10:18
https://github.com/iNavFlight/inav/pull/6430

**Comment by kasatka60** [comment] 2021-02-12 08:37
[#6333](https://github.com/iNavFlight/inav/pull/6333) Is it possible to increase the maximum to 1-2 km?
The surrounding fields are overgrown with bushes and in case of FS, I can damage the airplane or someone .

**Comment by MrD-RC** [comment] 2021-02-12 08:43
> [#6333](https://github.com/iNavFlight/inav/pull/6333) Is it possible to increase the maximum to 1-2 km?
> The surrounding fields are overgrown with bushes and in case of FS, I can damage the airplane or someone .

That is not how SAFEhomes is supposed to work. The safehome should be within your line of sight, to make sure the landing area is empty and SAFE to land in. You can’t do this 1-2km away.

**Comment by kasatka60** [comment] 2021-02-12 09:31
That is, I have to run 1-2 kilometers for the plane to land in the field in FS mode?

**Comment by MrD-RC** [comment] 2021-02-12 10:07
> That is, I have to run 1-2 kilometers for the plane to land in the field in FS mode?

This has been discussed before with you in the safehomes issue. Safehomes is not a remote landing solution. It is to be used for alternate landing spots where you can still see the model. It won’t suite everyone. However, the safety of the general public comes first. Please stop cluttering up this unrelated issue.

**Comment by shellixyz** [comment] 2021-02-14 17:00
#6602

**Comment by digitalentity** [comment] 2021-02-15 16:52
#6603

**Comment by OptimusTi** [comment] 2021-02-19 14:54
#6598  :)

**Comment by DzikuVx** [comment] 2021-02-23 11:14
@digitalentity are we doing this?

**Comment by DzikuVx** [comment] 2021-02-23 13:47
Thanks gents, the list is closed now. We will not release in 2.6.1 PR that were not either merged to master or approved or are changing the behavior that was not a bug.
So unfortunately some of the proposals were rejected.

**Comment by DzikuVx** [comment] 2021-02-23 13:47
The full list is:

https://github.com/iNavFlight/inav/pull/6584
https://github.com/iNavFlight/inav/pull/6418
https://github.com/iNavFlight/inav/pull/6320
https://github.com/iNavFlight/inav/pull/6327
https://github.com/iNavFlight/inav/pull/6462
https://github.com/iNavFlight/inav/pull/6499
https://github.com/iNavFlight/inav/pull/6477
https://github.com/iNavFlight/inav/pull/6602
https://github.com/iNavFlight/inav/pull/6603

**Comment by avsaase** [comment] 2021-02-24 09:53
No #6430?

**Closed as completed** 2021-02-25 14:19 UTC
