### ISSUE TITLE
Auto land regression in 1.6.2 (681b611)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#1428] opened 2017-03-18 17:01 UTC
In 1.6.1 and earlier, auto land has worked well, descending rapidliy at first, slowing down and disarming on landing:
```
set nav_land_slowdown_minalt = 400
set nav_land_slowdown_maxalt = 1000
set nav_mc_auto_disarm_delay = 500
````
On 1.6.2, yesterday I noticed that landing was extremely slow (http://seyrsnys.myzen.co.uk/inav-162-landing/LOG00001.TXT) (600mm tricopter). The descent from 24m to poweroff takes c. 70 seconds. (SPEvo)

Today I tried it on a 420mm quad (SPRF3.BMP280). Again, same symptoms, extremely slow initial descent. The machine then auto-disarmed at 16.4m; resulting in a more rapid descent, though not the intended effect. Fortunately the ground is extremely soft and the machine fell level, resulting in no damage. Unfortunately, the logger was not working.

The machine was reflashed to 1.6.1 and flown again. Auto land works perfectly. http://seyrsnys.myzen.co.uk/inav-162-landing/LOG00633_2.TXT ; the descent from 21m to power off is c. 12s.

I'm sorry for not having a log of the disarm at 16m incident; I must have failed to reconnect it after flashing 1.6,2. I'm also reluctant to try and get a log, as I doubt I will be so lucky a second time around. 

I wonder is the disarm is a symptom of whatever bugs us causing the slow down, as the disarm delay is 0.5 sec, and mega slow descent bug needs a longer delay to prevent false detection.

**Comment by stronnag** [comment] 2017-03-18 19:44
As I've been noticing annoying (but not fatal) slowdown in autoland, I decided to see how 1.6.x has performed. Other than the worst performing (in very slow) is 681b611, there's not much correlation and a large variation. I probably have BB logs for most of these (other than the above interesting one). Attached is a spreadsheet (CSV) ordered by autolanding rates in m/s for all 1.6.x tested (some of the git ids may be private merges which could be resolved).

[landing.txt](https://github.com/iNavFlight/inav/files/852696/landing.txt)

**Comment by digitalentity** [comment] 2017-03-18 22:36
@stronnag is that machine equipped with sonar? IIRC your sonar is reading 30-40cm all the time and autoland code will switch to slow landing if sonar is reading < 50cm.

**Comment by digitalentity** [comment] 2017-03-18 22:37
Disarm in the air is more worrying though - probably caused by too low threschold for throttle.

**Comment by stronnag** [comment] 2017-03-18 22:45
The tricopter which also suffers from slow land in 681b611 is not equipped with sonar. 

The quad has a different sonar sensor from last time (which I wanted to log!), but sonar was not enabled at the time of disarm.

So it looks possible that the sonar related changes are causing slow land unconditionally???

It was also quite windy, so the machine was being blown around a bit, 0.5s disarm timer is probably not too wise :)

**Comment by digitalentity** [comment] 2017-03-18 22:48
Okey, I'm now looking at your tri logs. Might be sonar related changes
indeed...

**Comment by stronnag** [comment] 2017-03-18 22:54
Ho ho, this will not be the first time I'm had a disarming result from sonar experiments. Still remarkable no damage falling 16m. 

And I deserve it, stronnag on RCG yesterday "_And testing even on development is far too tame at the moment._" That'll teach me.

**Comment by digitalentity** [comment] 2017-03-18 23:12
Found it. It was indeed new sonar code - wonar was always reported valid if enabled at compile-time. Apparently that was my doing :smiley:

**Comment by digitalentity** [comment] 2017-03-18 23:17
@stronnag fix ready https://github.com/iNavFlight/inav/pull/1430

**Comment by stronnag** [comment] 2017-03-19 07:09
Thanks. I will test it again as soon as possible, may not be today.

**Comment by digitalentity** [comment] 2017-03-19 08:08
Take you time. Thanks

**Comment by stronnag** [comment] 2017-03-19 14:31
Confirmed fixed on two different machined, 600mm tri and 280mm dead cat. Thanks.

**Comment by digitalentity** [comment] 2017-03-19 14:42
Cool! Fix merged!

**Closed as completed by digitalentity** 2017-03-19 14:42 UTC
