### ISSUE TITLE
PWM RC not working on CC3D

### ISSUE THREAD

**Issue by TradeCrafter** [iNavFlight/inav#880] opened 2016-12-08 01:11 UTC
https://www.youtube.com/watch?v=zT57Z4heyGw

you can see the oscillating issue on the video, the CC3D flashed with CleanFlight works fine, same with LibrePilot and OpenPilot...

so the only thing i can think of is a bug...

RADIO: FlySky FS-i6
RECEIVER: FS-iA6  6ch

**Comment by digitalentity** [comment] 2016-12-08 08:23
Dump? Bootlog?

**Comment by oleost** [comment] 2016-12-08 09:14
@TradeCrafter <strike>Just want to inform you that issues is confirmed and they are looking into it.</strike>

EDIT: Not confirmed, was an issue with equipment hookup on first test.

**Comment by digitalentity** [comment] 2016-12-08 09:24
@TradeCrafter can't reproduce the issue on my FrSky system using INAV-1.4 and all 6 PWM inputs. Please provide a config dump.

**Comment by TradeCrafter** [comment] 2016-12-08 10:42
it was not an hookup on first test, i mounted the F-450, flew and crashed, mounted again... the same issue, reviewed all the setup, wirings, solderings, i've also looked for possible interference, separate wires from power sources, magnetic fields, etc...

i don´t have any logs, right now i got this CC3D flashed with cleanflight, i needed to fly safe, hope to get back on iNAV when arrives my new i-BUS receiver.

**Comment by digitalentity** [comment] 2016-12-08 10:51
@TradeCrafter FYI, I have a FlySky system in transit. Will re-test and try to confirm the bug.

Also can you answer a few questions?

1. What version of INAV were you using?
1. What variant of CC3D firmware were you using (currently there are CC3D, CC3D_PPM1)
1. Did you configure OneShot, softserial or any other features?
1. If you have a CLI `dump` output - it would also be quite good to analyse.

**Comment by TradeCrafter** [comment] 2016-12-08 10:56
1,2= tryied: "inav_1.2.0_CC3D_OPBL.bin" and "inav_1.4.0_CC3D.hex"
3- no softserial, using telemetry on uart1, and GPS ublox on uart3, but i also set without this itens, only FC and r/c, still...
4- i dont have a CLI dump...  sorry

**Comment by digitalentity** [comment] 2016-12-08 11:03
Ok, I didn't try to test version **that** old (1.2 was relesed over 3 months ago and a lot of bugs was fixed since than). If  you have the time, can you try 1.4 and see if the bug persists?

**Comment by TradeCrafter** [comment] 2016-12-08 11:06
sorry my mistake, i updated my last comment, i try the last one for sure, this is the first one i tried...

**Comment by TradeCrafter** [comment] 2016-12-08 11:08
i think its not a matter of version... happens on both versions i tried.

**Comment by digitalentity** [comment] 2016-12-08 12:03
Ok, FlySky-specific then. This will have to wait until I get the hardware to test.

**Comment by digitalentity** [comment] 2016-12-21 11:51
Issue confirmed. @TradeCrafter will you be able to test the possible fix?

**Comment by digitalentity** [comment] 2016-12-21 12:07
See https://github.com/iNavFlight/inav/pull/956 for a fix

**Comment by TradeCrafter** [comment] 2016-12-21 18:14
i am using openpilot on the FC, but i can re-flash with inav again to try !!
just point me in the right directions ?
is the fix on a new FW release ?
i read "See #956 for a fix"  but just don't understand what to do, seems like any change needs to be done on some C file for handle with pwm capture...

i am happy to help man !

**Comment by digitalentity** [comment] 2016-12-22 08:09
@TradeCrafter I made you a hex (OPBL version doesn't fit into memory now). Please try this hex on your setup.

[inav_1.5.0_CC3D.hex.gz](https://github.com/iNavFlight/inav/files/668285/inav_1.5.0_CC3D.hex.gz)

**Comment by TradeCrafter** [comment] 2016-12-22 13:16
it worked like a charm, @digitalentity !! bug fixed!!  glad to help !!!

**Comment by digitalentity** [comment] 2016-12-22 13:48
@TradeCrafter thanks for testing!

**Comment by TradeCrafter** [comment] 2016-12-22 14:25
i'm having some trouble with my 915mhz 3dr telemetry, with older version of iNAV it worked... there's any change needs to be done in order to get it working ?

**Comment by digitalentity** [comment] 2016-12-22 14:27
What telemetry are you using? CC3D only supports LTM due to memory limitations

**Comment by TradeCrafter** [comment] 2016-12-22 15:04
china cheap ones, running SiK firmware, wich has on config utility the MAVLink or RAW DATA protocols, i read on iNAV wiki, about this forked firmware: https://github.com/stronnag/SiK-MSP

do you know by any means if theres is a chance to use it on my 3dr ?

**Comment by stronnag** [comment] 2016-12-22 15:08
You can run any protocol over it (MSP, LTM, Mavlink). The supplied firmware is optimised for mavlink framing, this does not preclude using MSP/LTM. Lots more detail in the wiki https://github.com/iNavFlight/inav/wiki/iNavFlight-Missions

**Comment by TradeCrafter** [comment] 2016-12-22 15:19
ok my radios are exactly these: [https://pt.aliexpress.com/item/3DRobotics-400mW-Telemetry-Kit-915Mhz-915-Module-For-APM-APM2-5-2-6-Pixhawk-For-Quad/32251253239.html?spm=2114.13010608.0.0.KtgjVq&detailNewVersion=&categoryId=200001407](url)

i dont have the silabs debug adapter, i got an USB/TTL adapter, can i use it instead ?
this firmware of yours will work on my hardware ?
it needs to get bootloader updated also ?

**Comment by stronnag** [comment] 2016-12-22 15:21
The modified firmware will work. I have the 433Mhz version. You can use an USB/TTL to update the firmware. You do not need to update the bootloader.

**Comment by TradeCrafter** [comment] 2016-12-22 15:33
last question: can i use the config utility from 3D Robotics, for windows, to perform the flash ?

**Comment by stronnag** [comment] 2016-12-22 15:41
Sorry, no experience of Windows. The GUI from http://vps.oborne.me/3drradioconfig.zip should work on Windows and Linux, for flashing and configuration.

**Comment by TradeCrafter** [comment] 2016-12-22 15:44
this is the GUI for windows i use, just cant get to compile the firmware for the radios, using VM on Mint, the ec2tools just wont install... 
it will be the same bin/hex file for the 2 radios ? air and ground ?

**Comment by TradeCrafter** [comment] 2016-12-22 15:55
can i use the: radio~hm_trp.ihx  ?

**Comment by stronnag** [comment] 2016-12-22 15:56
Same firmware for both (it is entirely symmetrical)
http://www.seyrsnys.myzen.co.uk/3dr/radio~hm_trp.ihx or the file from github.

**Comment by TradeCrafter** [comment] 2016-12-22 17:27
managed to upload the firmware, and get both radios sync, green lights remains still and get response on local and remote radios, on the FC, i've put LTM on "ports" tab, UART1, marked "telemetry" on "configuration" tab, got red blinks, but no conection with inav trough 3dr... i using 56.700 baudrate on my radios

**Comment by stronnag** [comment] 2016-12-22 17:31
So can you post the iNav serial setup (serial in the CLI), and the 3dr setup?

**Comment by TradeCrafter** [comment] 2016-12-22 18:36
looks like a joke... i got all 4 ESCs beeping th first 3 fast beeps, but the longer beep after it only came from 3 ESCs, one of them dont beep the second beep, it's okay before flahsing...  i need to go out now, later i will look furhter on telemetry... i just worried about this ESC... (simonk 30A, china red ones) 
:(

**Comment by TradeCrafter** [comment] 2016-12-22 23:23
MAAAAAAN !!!!! you made goo all across town here in Rio de Janeiro to buy another ESC, and when i get it into just doesn't work like the other one... so i flashed CopterControl firmware again and thats it !! ALL 4 ESCs and MOTORS ready to fly again... there´s something on the HEX you sent me...
and i got an different brand ESC for replace now.. i can't believe bro... the issue was on the firmware...

**Comment by digitalentity** [comment] 2016-12-22 23:26
Didn't you forget to enable ESC outputs in Configurator?

![image](https://cloud.githubusercontent.com/assets/11059099/21443512/cbcdb5cc-c8f1-11e6-8357-289fca046be9.png)

**Comment by digitalentity** [comment] 2016-12-22 23:32
PWM input is now fully functional, #956 is merged, closing this issue.

**Closed as completed by digitalentity** 2016-12-22 23:32 UTC
Labels: Bugfix, In progress

**Comment by TradeCrafter** [comment] 2016-12-23 00:18
without enabling esc output, no one motors spin... enabling it works only 3 motors...

**Comment by digitalentity** [comment] 2016-12-23 00:32
This is strange. From my bench-tests all motor outputs work fine on CC3D+PWM RX, I'll need to test this more, thanks.
