### ISSUE TITLE
Fly Time not counting up after "normal" (not auto) launch 2.0.0 RC2

### ISSUE THREAD

**Issue by kingdraki** [iNavFlight/inav#3559] opened 2018-07-10 15:47 UTC
### Board and Version
# INAV/OMNIBUSF4PRO 2.0.0 Jun 29 2018 / 12:34:56 (a8415e89c)

### Behavior
After normal hand launch the fly time does not start counting up, stays at 00:00.
Ater auto launch behaviour is as expected.

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/sbPpiHN4

**Comment by shellixyz** [comment] 2018-07-10 23:05
Duplicate of #3495. Already fixed for RC3.

**Closed as completed** 2018-07-10 23:09 UTC
