### ISSUE TITLE
Disable Failsafe in Waypoint Mode

### ISSUE THREAD

**Issue by Basti77** [iNavFlight/inav#4733] opened 2019-05-24 16:10 UTC
Is there a way to disable failsafe only in waypoint mode? With Andruplane this works without changing anything. 
I appreciate failsafe when I fly myself, but on a mission I don't care if the signal is gone. Only for landing I need the control again. In the meantime I relax

**Comment by digitalentity** [comment] 2019-05-24 19:28
Duplicate of https://github.com/iNavFlight/inav/issues/3937

**Closed as completed by digitalentity** 2019-05-24 19:28 UTC
