### ISSUE TITLE
Roll and Tilt Orientation are wrong after set Yaw Orientation not equal to "0"

### ISSUE THREAD

**Issue by Stoeny** [iNavFlight/inav#1671] opened 2017-05-13 14:36 UTC
After setting Yaw orientation to 90 deg or 270 deg in configurator, Roll- and Pitchorientation are exchanged.

**Comment by digitalentity** [comment] 2017-05-13 14:40
This is not a bug. Roll, Pitch and Yaw alighment are relative to the **board** - meaning it's how your frame is aligned against the board.

**Comment by DzikuVx** [comment] 2017-05-17 18:59
Closing

**Closed as completed by DzikuVx** 2017-05-17 18:59 UTC
