### ISSUE TITLE
SPracing F3 have problem at change "Receiver mode" to frimwares v2.2.0 and new

### ISSUE THREAD

**Issue by Explorer200** [iNavFlight/inav#5068] opened 2019-09-13 17:08 UTC
## Current Behavior

Have problem at change "Receiver mode" to frimwares v2.2.0 and new
## Steps to Reproduce

1. Update firmware to v2.2.0 or new
2. go to configurator
3. change Receiver mode PWM and other
4. save changes
5. Receiver mode have status NONE

## Expected behavior

I would like to select different modes

## Additional context

# version
# INAV/SPRACINGF3 2.2.0 Jun 18 2019 / 14:39:24 (5e5551bd3)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
---

- FC Board name and vendor:
- INAV version string:
MultiWii API version received - 2.3.0
Flight controller info, identifier: INAV, version: 2.2.0
Running firmware released on: Jun 18 2019 14:39:24
Board: SRF3, version: 0

**Comment by stronnag** [comment] 2019-09-13 17:17
Duplicate of #4986

**Closed as completed by stronnag** 2019-09-13 17:17 UTC
Labels: Bugfix
