### ISSUE TITLE
cant run inav on chrome

### ISSUE THREAD

**Issue by joelmatousek** [iNavFlight/inav#659] opened 2016-10-04 21:31 UTC
I was recently trying to run inav on my chrome, but when I run the file, it says "could not load manifest." 
How do I run  it, I am using chrome

**Comment by digitalentity** [comment] 2016-10-05 00:28
Unable to reproduce. INAV Configurator works fine. Possibly issues with your Google Chrome installation.

**Comment by DzikuVx** [comment] 2016-10-05 09:50
@joelmatousek also no problems here

**Comment by Ralf-W** [comment] 2016-10-05 19:06
Been there, done that: I downloaded the zip file from GITHUB and called it e.g. "inav-configurator-master_12.08.2016.zip". Unziping this archive results in a folder named "inav-configurator-master_12.08.2016" that contains a folder "inav-configurator-master". 
Opening "inav-configurator-master_12.08.2016" in Chrome results in "could not load manifest." 
Opening "inav-configurator-master" in Chrome results in successful installation of iNAV Configurtor.

**Comment by joelmatousek** [comment] 2016-10-05 19:09
@Ralf-W thanks! Tried it and it worked

**Comment by DzikuVx** [comment] 2016-10-05 19:44
OK, since solved, I'm closing

**Closed as completed by DzikuVx** 2016-10-05 19:44 UTC
