### ISSUE TITLE
Matek 3901-L0X - Add support for Altitude Hold Without Barometer

### ISSUE THREAD

**Issue by lavachemist** [iNavFlight/inav#6648] opened 2021-02-26 13:11 UTC
## Current Behavior
INAV currently requires a barometer for altitude hold when the Matek 3901-L0X is connected, even though the board has an onboard L0X rangefinder.

## Desired Behavior
Allow altitude hold and position hold without a GPS/Compass for indoor flight.

## Who does this impact? Who is this for?
This is for INAV users who want to fly indoors. A rangefinder is much better for altitude hold than a barometer in indoor situations. I've used this same board in Ardupilot and was surprised to see that it won't have full functionality in INAV.

## Additional context
Is there a technical reason why this was never implemented? The Matek 3901-L0X was specifically designed for INAV use and only supports MSP. It seems odd that you can't use it without a barometer.

**Comment by digitalentity** [comment] 2021-02-26 20:14
Duplicate of #6222

**Closed as completed by digitalentity** 2021-02-26 20:14 UTC
