### ISSUE TITLE
feature request GEOFENCE in INAV #62

### ISSUE THREAD

**Issue by JWC1304** [iNavFlight/inav#3524] opened 2018-07-05 20:28 UTC
Would it be possible to enable geofence in inav soon with some gui? 
Better yet , just using google maps?

**Comment by AnandNL** [comment] 2018-07-07 19:49
or steer to home after XXXX  meters

**Comment by fiam** [comment] 2018-07-07 20:10
Duplicate of #62. Please, add your feedback in that issue so we can keep all the comments in one place. Thanks!

**Closed as completed by fiam** 2018-07-07 20:10 UTC

**Comment by rhass** [comment] 2020-07-11 06:21
Geofencing should also support exclusion zones which would prevent flying into specific areas within a geofence. Eg: Buildings, trees, and communications towers.
