### ISSUE TITLE
No DSHOT on SpeedyBee F405V3 stack

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav#9285] opened 2023-09-08 18:05 UTC
## Current Behavior
Flashing the FC to V6.1.1 is no problem- works as intended. Yet INAV selects `Multishot` for the outputs/ESCs  and this spoils the connection when Bluejay is installed. The ESC is described as doing `DSHOT300` or `DSHOT600`. Unfortunately this option can't be saved/set so it falls back to `Multishot` and so won't work with Bluejay ... only with BLHELI_S

## Steps to Reproduce
1. Simply flash V6.1.1 to the FC (take 7" multi rotor)
2. Run Bluejay (esc-configurator) and flash 0.19.2 (?) the ESCs to Bluejay
3. INAV configurator won't run the motors as only `Multishot` possible 
4. Motors won't run

<img width="698" alt="image" src="https://github.com/iNavFlight/inav/assets/8381714/71bd4392-6053-4b89-b8b7-3ebfa12c2fa2">

## Expected behavior
It should be able to select DSHOT300/600 and make use of Bluejay

## Additional context
Link to Hardware and description : https://www.speedybee.com/speedybee-f405-v3-bls-50a-30x30-fc-esc-stack/
Link to pastebin dump: https://pastebin.com/Az2YBumz
---
# INAV/SPEEDYBEEF405V3 6.1.1 Jun 13 2023 / 12:27:32 (42ced253)
# GCC-10.2.1 20201103 (release)

**Comment by stronnag** [comment] 2023-09-08 18:33
Duplicate of #8817, #8910, #8919

**Closed as completed by stronnag** 2023-09-08 18:33 UTC
