### ISSUE TITLE
Failsafe RTH does not work on 1.7.3 - shuts down motors

### ISSUE THREAD

**Issue by stefan73** [iNavFlight/inav#2236] opened 2017-09-30 12:35 UTC
INAV 1.7.3 on SP Racing F3 in a FPV Racer quadcopter; PWM RX; UBlox GPS
RTH works fine when activated over remote. 
Failsave set to RTH.

--> Switch off remote. Motors immerdiately off and copter drops.

**Comment by fiam** [comment] 2017-09-30 13:27
@stefan73 It might be a configuration error. Please, post your config dump from the CLI so we can make sure everything is configured correctly.

**Comment by stefan73** [comment] 2017-09-30 13:43
@Here is the config. Looks fine at least in the configurator. As said before: Flies perfectly. RTH & Postion Hold ok. Remote off --> Drop instead of RTH.

````
# version
# INAV/SPRACINGF3 1.7.3 Sep  9 2017 / 10:20:09 (974440df)

# resources

# mixer
mixer QUADX

mmix reset


# servo
servo 0 1000 2000 1500 100 -1 
servo 1 1000 2000 1500 100 -1 
servo 2 1000 2000 1500 100 -1 
servo 3 1000 2000 1500 100 -1 
servo 4 1000 2000 1500 100 -1 
servo 5 1000 2000 1500 100 -1 
servo 6 1000 2000 1500 100 -1 
servo 7 1000 2000 1500 100 -1 

# servo mix
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature VBAT
feature MOTOR_STOP
feature GPS
feature RX_PARALLEL_PWM
feature LED_STRIP
feature BLACKBOX
feature PWM_OUTPUT_ENABLE

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE

# map
map AETR1234

# name
name -

# serial
serial 0 1 115200 38400 0 115200
serial 1 2 115200 9600 0 115200
serial 2 1 115200 38400 0 115200

# led
led 0 0,0:S:CTW:2
led 1 1,0:S:CTW:2
led 2 2,0:S:CTW:2
led 3 3,0:S:CTBW:5
led 4 4,0:S:CTBW:5
led 5 5,0:S:CTW:2
led 6 6,0:S:CTW:2
led 7 7,0:S:CTW:2
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 226,0,31
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 1 0 1800 2100
aux 1 1 0 1400 1600
aux 2 2 0 1600 1800
aux 3 20 0 1600 1800
aux 4 3 0 1800 2100
aux 5 9 0 1800 2100
aux 6 8 0 900 1400
aux 7 11 1 1800 2100
aux 8 12 1 900 1200
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1050 1950
rxrange 1 1950 1050
rxrange 2 1050 1950
rxrange 3 1050 1950

# master
set looptime = 1000
set gyro_sync = ON
set gyro_sync_denom = 4
set align_gyro = CW0
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 100
set moron_threshold = 32
set gyro_notch1_hz = 320
set gyro_notch1_cutoff = 200
set gyro_notch2_hz = 160
set gyro_notch2_cutoff = 100
set vbat_adc_channel = 1
set rssi_adc_channel = 3
set current_adc_channel = 2
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = CW0
set acc_hardware = MPU6050
set acc_lpf_hz = 15
set acczero_x = 146
set acczero_y = -25
set acczero_z = -799
set accgain_x = 4090
set accgain_y = 4103
set accgain_z = 4004
set rangefinder_hardware = NONE
set align_mag = CW0
set mag_hardware = HMC5883
set mag_declination = -300
set magzero_x = 52
set magzero_y = -142
set magzero_z = -76
set mag_calibration_time = 30
set baro_hardware = MS5611
set baro_use_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_invert = OFF
set rc_smoothing = ON
set serialrx_provider = SPEK1024
set sbus_inversion = ON
set rx_spi_rf_channel_count = 0
set spektrum_sat_bind = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set blackbox_rate_num = 1
set blackbox_rate_denom = 5
set blackbox_device = SPIFLASH
set min_throttle = 1020
set max_throttle = 2000
set min_command = 1000
set motor_pwm_rate = 4000
set motor_pwm_protocol = ONESHOT42
set failsafe_delay = 5
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1250
set failsafe_throttle_low_delay = 100
set failsafe_procedure = RTH
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gimbal_mode = NORMAL
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 42
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 25
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = OFF
set auto_disarm_delay = 5
set gps_provider = UBLOX
set gps_sbas_mode = AUTO
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_min_sats = 6
set deadband = 5
set yaw_deadband = 50
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = OFF
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 100
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 300
set nav_min_rth_distance = 500
set nav_rth_climb_first = ON
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = ON
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 1500
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1400
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1700
set nav_fw_bank_angle = 20
set nav_fw_climb_angle = 20
set nav_fw_dive_angle = 15
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 5000
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_timeout = 5000
set nav_fw_launch_climb_angle = 18
set telemetry_switch = OFF
set telemetry_inversion = ON
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set smartport_fuel_percent = OFF
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set i2c_speed = 400KHZ
set cpu_underclock = OFF
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = GYRO
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0

# profile
profile 1

set mc_p_pitch = 55
set mc_i_pitch = 40
set mc_d_pitch = 35
set mc_p_roll = 44
set mc_i_roll = 40
set mc_d_roll = 30
set mc_p_yaw = 70
set mc_i_yaw = 45
set mc_d_yaw = 20
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 5
set fw_i_pitch = 7
set fw_ff_pitch = 50
set fw_p_roll = 5
set fw_i_roll = 7
set fw_ff_roll = 50
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 600
set max_angle_inclination_pit = 600
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 180
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 60
set pitch_rate = 60
set yaw_rate = 60
set tpa_rate = 0
set tpa_breakpoint = 1500
````

**Comment by stronnag** [comment] 2017-09-30 15:56
If you get rid of the (insane) MOTOR_STOP feature does it work?

Certainly works for me (cyan in manual, yellow is RTH, big red text show why it's in RTH).
![image](https://user-images.githubusercontent.com/158229/31047310-1967ada6-a600-11e7-829f-a2d48f1d0570.png)

**Comment by stefan73** [comment] 2017-10-01 11:35
Thanks a lot. Confirmed. Failsafe RTH works ONLY if MOTOR_STOP is disabled. i.e. Motors must spin when armed and throttle min. Otherwise copter just drops.
I consider this as a major BUG. It is shocking to see that this bug seems to be around for more than a year now. I somewhen enabled MOTOR_STOP because I use an older RC without arm-switch on that model. It nearly costed me the copter that failsafe turned to drop silently.

If this is unfixable or difficult in INAV, at least the INAV configurator should actively block this configuration and warn about this configuration.

**Comment by digitalentity** [comment] 2017-10-01 12:28
@stefan73 interesting. We have code to disable motor stop automatically when failsafe activates. 
Can you show us screenshots of **Receiver** tab in Configurator when your TX is ON and when your remote TX is OFF?

**Comment by stefan73** [comment] 2017-10-01 12:41
Sure. I can also describe this. Failsafe on the "cheap" RC that I used for the tests puts everything on center and throttle to low, when you switch off. Bad thing is that this is unchangable on a lot of cheaper RCs.
Let me know if you still need the screenshot.

**Comment by digitalentity** [comment] 2017-10-01 12:49
@stefan73 yes, I still need the screenshots. I think I know where the bug lurks, but I'm not sure if it's fixable at all. Screenshots will confirm.

**Comment by stefan73** [comment] 2017-10-01 13:15
Made two screenshots:
RC-on - copter on, RC on & connected
RC-off - after switching RC off
![rc-off-2017-10-01 15_11_20-inav - configurator](https://user-images.githubusercontent.com/11725734/31054825-36c5c796-a6bb-11e7-992e-93c8b973e424.png)
![rc-on-2017-10-01 15_10_42-inav - configurator](https://user-images.githubusercontent.com/11725734/31054828-3ee544a6-a6bb-11e7-8b9a-121d728a7b73.png)

**Comment by digitalentity** [comment] 2017-10-01 13:19
Does your copter correctly recognize that RC is off?

![image](https://user-images.githubusercontent.com/11059099/31054858-d5b9555a-a6fe-11e7-907a-4ffdc2a9d363.png)

Also, I see that when your RC is turned off AUX2 goes to 2000. Is this how failsafe is configured on the receiver?

**Comment by stefan73** [comment] 2017-10-01 13:51
The upper images are mixed up. Aux1 is at 1100 when RC is off. As said not configurable on this RC.
When I hook the copter up to the laptop, attach battery, bind RC and disarm, the props spin now. When I turn the RC off, the red parachute does not come. Maybe I do something wrong here.
When I fly with MOTOR_STOP off and turn off the RC, it comes back home. So I guess it recognizes the the RC is off.

**Comment by digitalentity** [comment] 2017-10-01 13:59
Ok, so when your RC is off, throttle channel goes down to approx. 889.
This is on the edge of detecting invalid signal (which may explain why sometimes it works).

Try setting `set rx_min_usec = 900` in CLI and don't forget to do `save`. This will ensire that when your RC is off, throttle channel goes to a invalid value that will trigger failsafe.

In general - you need to make sure that red parachute lights up when you turn off the transmitter. Also, using receivers that don't have programmable failsafe is not a good idea.

**Comment by stefan73** [comment] 2017-10-01 14:42
I see the point. Thanks. I do agree that the cheap remote might be too cheap because you cannot set failsafe.
Still I am wondering, why it reproducibly flies homes with MOTOR_STOP disabled and falls from the sky with MOTOR_STOP enabled.

**Comment by fiam** [comment] 2017-10-02 20:14
I think we should investigate this one further. It doesn't make sense that RTH via FS worked without MOTOR_STOP and dropped with MOTOR_STOP.

Also, if the problem was that THR = 889us wasn't triggering FS, the copter should have gone to the ground rather than RTH when MOTOR_STOP was disabled.

**Comment by digitalentity** [comment] 2017-10-04 08:46
I agree, this needs to be investigated. Changing the lablel to "Bug"

**Comment by stefan73** [comment] 2017-10-14 15:23
Bad news in terms of reproducability. I killed the remote that was involved into this. This made me switch to an rc with arm switch and ibus communication. So I cannot reproduce it any more. Sorry for that.

**Comment by digitalentity** [comment] 2017-10-15 05:47
@stefan73 same here. Unable to reproduce neither on Taranis (with variety of receivers) nor on FlySky (IBUS, SBUS & PPM tested)

**Comment by digitalentity** [comment] 2017-10-18 00:46
We are disabling MOTOR_STOP for RTH & WP - might mitigate issues with throttle stick being at zero when failsafe happens or RTH is activated. Closing.

**Closed as completed by digitalentity** 2017-10-18 00:46 UTC
Labels: Bugfix
