### ISSUE TITLE
HW - Support F4-based targets

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#130] opened 2016-03-24 03:44 UTC
Some support for F4 is done by @sambas already, it has to be ported to iNav

**Comment by Linjieqiang** [comment] 2016-03-24 04:40
Great~! I'm going to design a flight control board for this firmware.The detailed list includes STM32F407,MPU9250,M8N GPS,MS5611~!

**Comment by digitalentity** [comment] 2016-03-24 04:53
@Linjieqiang amazing! 
My few cents regarding new FC:
1. Please consider using MPU6500 as it doesn't include the magnetometer
2. Place the gyro on SPI bus for faster communication
3. You may want to use MS5607 baro - it's much cheaper and accurate enough
4. If you are going to design a GPS module as well, please consider using NXP MAG3110 chip as HMC mag chips are EOL
5. Don't include a voltage regulator onboard. It takes space and makes the FC less crash-proof
6. Use level shifters (3.3V - 5V) for SONAR Echo and LEDSTRIP pins to make operation noise-proof.

**Comment by Linjieqiang** [comment] 2016-03-24 05:21
I suggest you should design a flight board and support the inav project perfectly fine like SPrcaingF3.The GPS module will be bought from Taobao.yeah,I will design for sonnar~!I will think about your suggestion.Thanks

**Comment by brat002** [comment] 2016-03-25 17:44
Please, add support of Sparky 2.0.

**Comment by ScienceFaction** [comment] 2016-05-06 21:29
Please add support for elle0 http://1bitsquared.com/products/elle0-autopilot
http://wiki.paparazziuav.org/wiki/Elle0
Its an F4 board with the sensors on an spi bus designed for paparazzi.
As paparazzi is open source getting the necessary porting info may be straight forward.

**Comment by digitalentity** [comment] 2016-05-06 22:36
@Linjieqiang @ScienceFaction @brat002 
I don't have any F4-based hardware to debug and test so this proibably won't happen any time soon. Sorry.

**Comment by ScienceFaction** [comment] 2016-05-06 22:39
@digitalentity How about if I get you an elle0?

**Comment by digitalentity** [comment] 2016-05-06 22:42
@ScienceFaction 
Then I'll get it working in INAV in a month or two (depending on how much time I have to spare). Drop me a message (my email address is in my GitHub profile).

**Comment by martinbudden** [comment] 2016-07-09 07:41
Closing, duplicate of issue https://github.com/iNavFlight/inav/issues/274

**Closed as completed by martinbudden** 2016-07-09 07:41 UTC
Labels: Enhancement
