### ISSUE TITLE
MSP RX input doesn't work

### ISSUE THREAD

**Issue by anbello** [iNavFlight/inav#666] opened 2016-10-05 08:36 UTC
If I choose RX_MSP as Receiver Mode on Configuration tab then on Receiver tab I have no channels, "Control sticks" have no effect and if I use MSP program to send RC commands (EZ-GUI on Android or PyMultiWii on PC) they have no effect.
Sometime ago I did it with cleanflight and it worked, maybe with iNav I have to do some other setting in other place.

**Comment by anbello** [comment] 2016-10-07 09:33
Maybe no one answered because of the number of this issue :)

**Comment by oleost** [comment] 2016-10-07 09:46
Or if you provided more information? 

What board, what iNav version, cli dump, verify that the same method your using now are still working in Cleanflight. 

How do you have everything connected up?

**Comment by anbello** [comment] 2016-10-07 10:33
Sorry

I have the same problem with two quad:
1) naze32 10dof rev6 (clone from banggood) with iNav 1.2
2) SP Racing F3 brushed with iNav 1.2.1

for both I have an esp8266 wifi serial bridge connected to uart1 that works with ez-gui for telemetry but not for control (as I said before)

for 2) I tried the same method with last cleanflight and it worked

When I return to home from my work I will post some dump

**Comment by oleost** [comment] 2016-10-07 10:34
Can you try iNav 1.1 as well to see if it works there?

**Comment by martinbudden** [comment] 2016-10-07 10:48
It is possible that some of my receiver changes broke this. Unfortunately I won't be able to look at this until late next week.

**Comment by anbello** [comment] 2016-10-07 11:27
In this week end I can try with iNav 1.1 and I will report here.

**Comment by digitalentity** [comment] 2016-10-07 11:33
If this is a bug, it should go into 1.3

**Comment by anbello** [comment] 2016-10-11 12:25
What I said before is partially incorrect.
On the SP Racing F3 brushed with iNav 1.2.1 if I set RX_MSP as Receiver Mode it works.
On the Naze32 rev6 with iNav 1.2 and 1.2.1 it doesn't works (as I said above). If I re-flash iNav 1.1 I have the correct behaviour and RX_MSP as Receiver Mode  works.

**Comment by stronnag** [comment] 2016-10-11 12:35
That is because RX_MSP is only enabled for targets with > 128K flash (see src/main/target/common.h)

This is a feature.

Further if I remove `#define SKIP_RX_MSP` from the above file, RX_MSP works OK (at least on a flip32), which a simple simulator and monitored in the configurator.

**Comment by martinbudden** [comment] 2016-10-11 16:28
RX_MSP was removed from the sub 128K targets as a ROM saving measure. So this is deliberate and not a bug. Closing issue.

**Closed as completed by martinbudden** 2016-10-11 16:28 UTC

**Comment by anbello** [comment] 2016-10-11 19:35
Thanks and sorry for having wasted your time, I did not know that this feature had been removed.

**Comment by martinbudden** [comment] 2016-10-11 19:42
@anbello - no worries. But reports are always welcome.

**Comment by digitalentity** [comment] 2016-10-12 00:47
@anbello, @martinbudden wiki updated to reflect lack of MSP RX support on NAZE & CC3D
https://github.com/iNavFlight/inav/wiki/Hardware-and-feature-support-map
