### ISSUE TITLE
Pulses for Servo Midpoint

### ISSUE THREAD

**Issue by jstremmler** [iNavFlight/inav#1854] opened 2017-07-02 13:47 UTC
I tried to replace the  NAZE32 FC on my Titus Tricopter by a (little) more modern  SPRACINGF3  FC but had to reinstall my NAZE.
What happened is that the SPRACINGF3 showed a very strange behavior for the servo (connected to PIN 7, motors 1-3 connected to Pin 1-3 of the FC) Although the servo_center_pulse rate was set to 1500 the FC showed an output of 1254 pulses to be seen for servo6 in the motor menue of the configurator. 

In contrast the NAZE showed  correctly 1500 pulses for servo 6 when servo_center_pulse was set to 1500.

Ok, I could have manipulated the pulses for the SPRACINGF3 by setting the servo_center_pulse rate to 1747, but servo movements were a little "strange" with the SPRACINGF3, so I decided to take no risk and reinstalled my NAZE.....

**Comment by stronnag** [comment] 2017-07-02 14:06
Strange. I don't believe this is a generic problem. Behaves as expected here (on two different vehicles for as long as I can recall). This is SPRF3.
![screenshot-20170702145906-1259x547](https://user-images.githubusercontent.com/158229/27770474-42f11dfc-5f37-11e7-8509-7fbdc65d01d3.png)

fwiw [cli diff](https://transfer.sh/j4hJD/mini-tri-inav.txt) (digital servo alert!).

**Comment by jstremmler** [comment] 2017-07-03 03:45
Well I did a quick and dirty test if this is a generic iNav problem or a specific problem of my FC.

I installed  Betaflight 3.1.7 on the same !!! SPRF3 and pulses for servo no. 6 in the motor menue were exactly at 1500 pulses. 
Next I flashed back iNav 1.7.1 and got 1253 pulses for servo no. 6. 

So is this really a specific problem of my FC?

**Comment by digitalentity** [comment] 2017-07-03 04:36
Please provide settings dump.

**Comment by jstremmler** [comment] 2017-07-03 06:41
Ok, here is the CLI file.

[Titus_CLI_SPRF3.txt](https://github.com/iNavFlight/inav/files/1118607/Titus_CLI_SPRF3.txt)
![titus1](https://user-images.githubusercontent.com/15327312/27781337-b11de6f2-5fcd-11e7-8d60-c3bffae6aadc.jpg)

**Comment by digitalentity** [comment] 2017-07-09 13:32
Can't reproduce the bug on 1.7.2 and your dump:
![image](https://user-images.githubusercontent.com/11059099/27994319-ce13f50e-64fe-11e7-89d7-8f06a9ba30cf.png)

Either the bug is no longer relevant, or we accidentally fixed it with latest changes to servo mixer by @DzikuVx

**Comment by DzikuVx** [comment] 2017-07-28 13:50
@jstremmler Since we can not reproduct, I'm closing this one. If issue still exists with INAV 1.7.2 and latest version of Configurator, please reopen and provide a configuration dump for further analysis

**Closed as completed by DzikuVx** 2017-07-28 13:50 UTC
