### ISSUE TITLE
V2.0.0 RC2 Flight Time alsways 00:00

### ISSUE THREAD

**Issue by Gregmaan** [iNavFlight/inav#3495] opened 2018-07-01 17:59 UTC
In the OSD Display the flight time shows always 00:00 during flight and in summary, using the "On Time / Fly Time" Timer in OSD setup.
diff:
https://pastebin.com/jF22efqs

**Comment by shellixyz** [comment] 2018-07-02 22:13
I'm using the "On Time / Fly Time" timer and can't reproduce the issue.

Not directly related to this issue: your battery capacity warning/critical thresholds are not configured correctly. Warning should be greater than critical. They represent the remaining mAh/mWh you want the thresholds to be triggered at. Please read the [battery management documentation](https://github.com/iNavFlight/inav/blob/development/docs/Battery.md#battery-capacity-monitoring) for more information.

**Comment by renatobfa** [comment] 2018-07-03 02:44
![timer](https://user-images.githubusercontent.com/32551670/42196407-3670a4f2-7e54-11e8-94ed-4486eac0e9a8.jpg)
> In the OSD Display the flight time shows always 00:00 during flight

Mine too.. Im flying with an Omnibus F4 Pro, I've also had this problem, showing always 00:00 after arming and in flight.

**Comment by teckel12** [comment] 2018-07-03 03:47
Also running Omnibus F4 Pro and my "On Time / Fly Time" OSD is just fine.

**Comment by Gregmaan** [comment] 2018-07-03 09:37
I think I found something:
If I start the flight with launch mode, the timer works.
So there could be an issue with flight detection without using launch mode.

**Comment by teckel12** [comment] 2018-07-03 13:06
@Gregmaan I launch with switch.

**Comment by Gregmaan** [comment] 2018-07-03 13:20
@teckel12 Do you mean launch mode on switch?
Before I did not use any launch mode ( with the issue).
Now I use Launch mode as feature and fly time is fine.

**Comment by shellixyz** [comment] 2018-07-03 13:40
Thank you for the report it will be fixed in the next RC. Indeed it happens when not using launch mode on fixed wing.

**Comment by fiam** [comment] 2018-07-07 19:36
Fixed by @shellixyz on #3509, will be on RC3

**Closed as completed by fiam** 2018-07-07 19:36 UTC
