### ISSUE TITLE
Zero throttle during RTH disables i-term for yaw

### ISSUE THREAD

**Issue by theArchLadder** [iNavFlight/inav#157] opened 2016-04-10 20:11 UTC
During the landing phase of RTH, it looks like zero throttle with stick arming disables the i-term for yaw, so the heading will not be locked in.

On the other hand, with i-term active, i had problems with windup when my quad had landed, i guess the uneven terrain gave a small heading change on touchdown that could not be corrected with the landing legs on the ground. This windup made two of the motors spin up at high rpm.

Not sure what the best solution is, how about having i-term active but more constrained?

**Comment by DzikuVx** [comment] 2016-04-10 20:16
I tend to agree with this observation. During todays experiments with Yaw I term I ended up in a situation that caused loose of stability and crash. I have low yaw performance and when mixer was trying to satisfy yaw it had not enough power on other axises.
Either that, or prop broke in mid air...

**Comment by stronnag** [comment] 2016-04-10 20:19
I've noticed this too. if I throttle down during RTH land then yaw lock is lost, even with airmode on.

**Comment by theArchLadder** [comment] 2016-04-10 20:34
@DzikuVx betaflight 2.5.2 has this in the changelog:
"Added piroutte protection during hard yaw manouvres. Yaw should not dominate over roll and pitch in some scenarios"
Sounds like something that could be helpful for you...? Has this been implemented in iNav?

**Comment by DzikuVx** [comment] 2016-04-10 20:42
@theArchLadder No, it was not. Perhaps it's worth taking from betaflight. 
@digitalentity it was introduced via c9a35d278d97963ae82c03a57ec93f161bee94f3 but I don't think it would solve my problem

**Comment by digitalentity** [comment] 2016-04-11 01:20
@DzikuVx yes, it's definitely worth taking. However here is the interesting part - it's not part of betaflight anymore...

**Comment by digitalentity** [comment] 2016-04-11 01:48
It would be better to prevent integration or even reset yaw integral if requested yaw rotation rate is high enough.

**Comment by digitalentity** [comment] 2016-05-04 03:03
@DzikuVx, @theArchLadder, @stronnag 
Can you confirm that the issue is still present with latest master? I believe #160 should fix it.

**Comment by DzikuVx** [comment] 2016-05-04 07:24
As soon as I will be able

**Comment by theArchLadder** [comment] 2016-05-04 10:04
I just remembered this on the last RTH i did just now. Based on this single test it did look like this issue is still present, when i cut the throttle the yaw started to wander and it had different behavior on the ground depending on throttle at zero or not.

Will hopefully do more tests later today.

**Comment by digitalentity** [comment] 2016-05-04 10:09
@theArchLadder, I've deliberately reduced PID authority at throttle below min-check (similar to way it's done in Betaflight). Maybe issue is this line: https://github.com/iNavFlight/inav/blob/master/src/main/flight/pid.c#L271

**Comment by theArchLadder** [comment] 2016-05-04 10:16
@digitalentity, sorry, i don't understand. This issue is about no i-gain when throttle is at zero, how is "reduced PID authority" related to this?

I think it would make sense to limit the authority of i-term so that we do not have so much windup/spool-up of the motors while on the ground, this seems like a separate issue, but perhaps this is what you meant?

**Comment by digitalentity** [comment] 2016-05-04 10:21
Heading lock overrides rcCommand[YAW] to maintain heading. Zero throttle + stick arming blocks rcCommand[YAW] at low throttle, so it's possible that the issue is in stick arming, not I-term itself

**Comment by theArchLadder** [comment] 2016-05-04 10:22
That does sound more likely, but why would the heading change then?

**Comment by digitalentity** [comment] 2016-05-04 10:23
Blackbox log will clarify the situation if you have one.

**Comment by digitalentity** [comment] 2016-05-09 01:17
I-term reset at zero throttle finally confirmed.
EDIT: It's not actually reset, but a side-effect of low-throttle PID attenuation.

**Comment by digitalentity** [comment] 2016-05-09 01:56
Should be fixed now. I-term at zero throttle requires AIR MODE to be enabled.
This commit doesn't attenuate I-term at zero throttle and also fixes some bugs in anti-windup handling.

**Comment by digitalentity** [comment] 2016-05-09 01:56
Please test and re-open if still present.

**Comment by theArchLadder** [comment] 2016-05-10 12:06
I just tried RTH with zero throttle now.
It does **not** change the heading at all
It goes up in altitude, but it does not care about altitude when flying home so it sort of slowly falls and crashes at the home location.

Works as expected with mid throttle though.
Not sure if i can re-open this issue myself...?

**Comment by digitalentity** [comment] 2016-05-10 12:12
@theArchLadder so it does change heading or it doesn't change heading? Also do you stick arm?

As for loosing altitude during RTH - interesting. This shouldn't happen - pilot should be locked out of altitude control at RTH. Can you open a separate issue for this phenomenon?

**Comment by theArchLadder** [comment] 2016-05-10 12:18
@digitalentity Sorry, it does not. Yes i use stick arm.

I will open a new issue in a moment.

**Comment by digitalentity** [comment] 2016-05-10 12:20
Stick arming completely disables Yaw control at zero throttle. This is going to be like this until we introduce new MAG HOLD controller as a part of fp-pid code.

**Comment by DzikuVx** [comment] 2016-05-10 12:23
On what I'm working currently BTW

**Comment by theArchLadder** [comment] 2016-05-10 12:23
It should still keep the current heading, right? I assume it behaves as if yaw stick was centered?

I have seen the heading change during the landing phase of RTH when throttle is at zero.

**Comment by digitalentity** [comment] 2016-05-10 12:31
@theArchLadder current MAG HOLD works by emulating Yaw stick input that's being ignored later by stick-arming code. What you are seing is probably arbitrary heading drift. MAG HOLD has no authority at zero throttle.
@DzikuVx is up to something better :wink:

**Comment by theArchLadder** [comment] 2016-05-10 12:50
@digitalentity Sorry but i still don't understand, there is no heading drift even in rate mode...? The I-term for the yaw-pid-controller prevents this.

**Comment by theArchLadder** [comment] 2016-05-11 08:11
I feel stupid now, i-term is disabled at zero throttle when using stick arming, even in rate mode... How about using airmode during RTH? Or perhaps that's already used...?

**Comment by DzikuVx** [comment] 2016-05-31 12:18
I had a chance to observe this last weekend. Then throttle is zeroed during landing, heading is no longer kept. Looks strange and little scary

**Comment by theArchLadder** [comment] 2016-05-31 12:30
@DzikuVx Did you use stick arming?
The roll and pitch also becomes unstable for me, i guess this is because rate I-term is disabled... Would it work to have airmode active with this?

This is actually also a problem in althold+poshold for me, My hover throttle stick is just at 25% so i usually bring the throttle stick to 0 if i want to descend, but at that point roll and pitch becomes unstable.

**Comment by DzikuVx** [comment] 2016-05-31 12:32
No, I use AUX switch. Unfortunately I do not remember if it was AIR MODE or not. Probably not

**Comment by theArchLadder** [comment] 2016-06-02 18:54
I did a quick test with airmode, but i didn't notice any improvement.

So this issue is not specific to yaw, and not stick arming either.
The rate I-term disabling with zero throttle seems to make copter unstable, but if we fix that we will have motor spool-up on the ground...

**Comment by digitalentity** [comment] 2016-09-01 01:10
I wonder if we should close this one

**Closed as completed** 2016-11-21 13:21 UTC
Labels: Bugfix
