### ISSUE TITLE
inav 1.7.3 failed with ScitE Editor

### ISSUE THREAD

**Issue by ampere-dieter** [iNavFlight/inav#2135] opened 2017-09-14 12:00 UTC
Hi all,
since inav 1.7.3 make with SciTE (V.4.0.0) failed with this message:
...
%% timer.c 
c:/users/wuertenberger/gnu_tools/build_tools/bin/sh: git: not found
settings.yaml -> settings_generated.h, settings_generated.c
c:/users/wuertenberger/gnu_tools/build_tools/bin/sh: ruby: not found
Makefile:932: recipe for target 'src/main/fc/settings_generated.h' failed
make: *** [src/main/fc/settings_generated.h] Error 127
>Exit code: 2

With inav 1.7.2 and all BetaFlight version I have no problems.

thanks for helps,
Dieter

**Comment by digitalentity** [comment] 2017-09-14 12:02
Duplicate of #2115

**Closed as completed by digitalentity** 2017-09-14 12:02 UTC

**Comment by stronnag** [comment] 2017-09-14 12:04
You need to install ruby. See release note and developer documents.

**Comment by ampere-dieter** [comment] 2017-09-14 12:20
thanks stronnag for Your fast help.
With ruby installed all things are as usual...
Dieter
