### ISSUE TITLE
Distance to home disappears from OSD when distance exceeds 1000m (.62mi) 1.8 RC2

### ISSUE THREAD

**Issue by snowblind64** [iNavFlight/inav#2419] opened 2017-10-27 03:08 UTC
After updating to iNav 1.8 RC2 when I fly more than 1000m, the distance to home in the OSD disappears. It reappears when I return to less than 1000m from launch. I have updated the fonts and did not have this issue with RC1.

I am running an Omnibus F4 Pro. Flying wing configuration.

Is anyone else having this issue?

**Comment by digitalentity** [comment] 2017-10-27 03:08
@fiam can you have a look?

**Comment by fiam** [comment] 2017-10-27 15:36
@snowblind64 It seems to work fine both in metric and imperial units for me. Does it disappear completely or does it just blink? If it's blinking, note that 1000m is the default value for the distance alarm, so you might be triggering it. Note that it can be configured or completely disabled from the configurator if it bother you.

Also, if you can post the video from the OSD output it might be helpful.

**Comment by snowblind64** [comment] 2017-10-27 18:29
@fiam The distance value disappears completely and does not return until I come back to <1000m from home. I have my distance alarm set to 2 miles and am using imperial units. I'm going to do some flying this afternoon and will do a bit more troubleshooting. If the problem persists I will post the DVR footage.

**Comment by teckel12** [comment] 2017-10-27 18:42
I just flew today with the latest development branch and when I exceeded 999m it showed the distance in miles. I never had anything flash or disappear. I have my max distance set to 1/2 mile so I wouldn't expect it to flash either.

**Comment by fiam** [comment] 2017-10-27 20:06
@snowblind64 Thanks for the clarification. I ran several bench tests, mocking the distance and making it go from zero to 3km and back and it worked fine. Hopefully the DVR footage will help us figure this one out.

**Comment by digitalentity** [comment] 2017-10-28 03:03
@snowblind64 I believe we need your full `dump` to see if this is a configuration error.
@fiam FIY I also did a synthetic test on my bench and distance is shown correctly.

**Comment by teckel12** [comment] 2017-10-28 03:59
I'll do a field test of flying further than 1000m tomorrow and see what happens. I always have the DVR running so I'll be able to review it.

**Comment by snowblind64** [comment] 2017-10-28 06:20
Seems the issue is related to the alarm blinking functionality. Sadly it seems to be intermittent. I am not seeing the distance or altitude blink when I exceed their alarm value. Most of the time it just remains solid.

On the last flight of the day I exceeded the 400ft alarm altitude I had set and altitude disappeared from the OSD, then returned when I dropped down again. I didn't have any issues with the distance today.

Could this be related to the blinking functionality? Perhaps it is caused by the timing at which point the alarm value is triggered. Unfortunately my DVR wasn't recording at the time. I'll see if I can replicate the issue tomorrow.

**Comment by snowblind64** [comment] 2017-10-28 06:22
Here's a full dump of my config:
`# dump

# version
# INAV/OMNIBUSF4PRO 1.8.0 Oct 24 2017 / 07:05:30 (0f1975ce)

# resources

# mixer
mixer FLYING_WING

mmix reset


# servo
servo 0 1000 2000 1500 100 -1 
servo 1 1000 2000 1500 100 -1 
servo 2 1000 2000 1500 100 -1 
servo 3 1100 2000 1500 -100 -1 
servo 4 1000 2000 1620 100 -1 
servo 5 1000 2000 1500 100 -1 
servo 6 1000 2000 1500 100 -1 
servo 7 1000 2000 1500 100 -1 

# servo mix
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -RX_UIB
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DASHBOARD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SUPEREXPO
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -PWM_SERVO_DRIVER
feature -PWM_OUTPUT_ENABLE
feature -OSD
feature VBAT
feature MOTOR_STOP
feature GPS
feature TELEMETRY
feature AIRMODE
feature PWM_OUTPUT_ENABLE
feature OSD

# beeper
beeper RUNTIME_CALIBRATION
beeper HW_FAILURE
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACTION_SUCCESS
beeper ACTION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper LAUNCH_MODE
beeper CAM_CONNECTION_OPEN
beeper CAM_CONNECTION_CLOSED

# map
map TAER5678

# name
name -

# serial
serial 20 1 115200 38400 0 115200
serial 0 0 115200 38400 0 115200
serial 2 2 115200 57600 0 115200
serial 5 64 115200 38400 0 115200

# led
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 0 0 1300 2100
aux 1 1 1 1300 2100
aux 2 3 2 1300 1700
aux 3 3 1 1700 2100
aux 4 9 2 1300 1700
aux 5 8 2 1700 2100
aux 6 10 0 1300 1650
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# master
set looptime = 1000
set gyro_sync = ON
set gyro_sync_denom = 1
set align_gyro = DEFAULT
set gyro_hardware_lpf = 188HZ
set gyro_lpf_hz = 60
set moron_threshold = 32
set gyro_notch1_hz = 0
set gyro_notch1_cutoff = 1
set gyro_notch2_hz = 0
set gyro_notch2_cutoff = 1
set vbat_adc_channel = 2
set rssi_adc_channel = 3
set current_adc_channel = 1
set airspeed_adc_channel = 0
set acc_notch_hz = 0
set acc_notch_cutoff = 1
set align_acc = DEFAULT
set acc_hardware = MPU6000
set acc_lpf_hz = 15
set acczero_x = 174
set acczero_y = -88
set acczero_z = -84
set accgain_x = 4086
set accgain_y = 4111
set accgain_z = 3995
set rangefinder_hardware = NONE
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 1330
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set mag_calibration_time = 30
set baro_hardware = BMP280
set baro_use_median_filter = ON
set pitot_hardware = NONE
set pitot_use_median_filter = ON
set pitot_noise_lpf =  0.600
set pitot_scale =  1.000
set receiver_type = SERIAL
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 8
set rssi_scale = 100
set rssi_invert = OFF
set rc_smoothing = ON
set serialrx_provider = CRSF
set sbus_inversion = ON
set rx_spi_rf_channel_count = 0
set spektrum_sat_bind = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SDCARD
set sdcard_detect_inverted = ON
set min_throttle = 1065
set max_throttle = 2000
set min_command = 1005
set motor_pwm_rate = 4000
set motor_pwm_protocol = ONESHOT42
set failsafe_delay = 10
set failsafe_recovery_delay = 5
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_throttle_low_delay = 0
set failsafe_procedure = RTH
set failsafe_stick_threshold = 50
set failsafe_fw_roll_angle = -200
set failsafe_fw_pitch_angle = 100
set failsafe_fw_yaw_rate = -45
set failsafe_min_distance = 0
set failsafe_min_distance_procedure = DROP
set align_board_roll = 10
set align_board_pitch = -35
set align_board_yaw = 1800
set gimbal_mode = NORMAL
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 265
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set servo_center_pulse = 1500
set servo_pwm_rate = 160
set servo_lpf_hz = 20
set flaperon_throw_offset = 200
set tri_unarmed_servo = ON
set reboot_character = 82
set imu_dcm_kp = 2500
set imu_dcm_ki = 50
set imu_dcm_kp_mag = 10000
set imu_dcm_ki_mag = 0
set small_angle = 180
set fixed_wing_auto_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set gps_provider = UBLOX7
set gps_sbas_mode = WAAS
set gps_dyn_model = AIR_1G
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_min_sats = 6
set deadband = 2
set yaw_deadband = 2
set pos_hold_deadband = 20
set alt_hold_deadband = 50
set 3d_deadband_throttle = 50
set fw_autotune_overshoot_time = 100
set fw_autotune_undershoot_time = 200
set fw_autotune_threshold = 50
set fw_autotune_ff_to_p_gain = 10
set fw_autotune_ff_to_i_tc = 600
set inav_auto_mag_decl = ON
set inav_gravity_cal_tolerance = 5
set inav_use_gps_velned = ON
set inav_gps_delay = 200
set inav_reset_altitude = FIRST_ARM
set inav_max_surface_altitude = 200
set inav_w_z_surface_p =  3.500
set inav_w_z_surface_v =  6.100
set inav_w_z_baro_p =  0.350
set inav_w_z_gps_p =  0.200
set inav_w_z_gps_v =  0.500
set inav_w_xy_gps_p =  1.000
set inav_w_xy_gps_v =  2.000
set inav_w_z_res_v =  0.500
set inav_w_xy_res_v =  0.500
set inav_w_acc_bias =  0.010
set inav_max_eph_epv =  1000.000
set inav_baro_epv =  100.000
set nav_disarm_on_landing = OFF
set nav_use_midthr_for_althold = OFF
set nav_extra_arming_safety = ON
set nav_user_control_mode = ATTI
set nav_position_timeout = 5
set nav_wp_radius = 5000
set nav_wp_safe_distance = 10000
set nav_auto_speed = 300
set nav_auto_climb_rate = 500
set nav_manual_speed = 500
set nav_manual_climb_rate = 200
set nav_landing_speed = 200
set nav_land_slowdown_minalt = 500
set nav_land_slowdown_maxalt = 2000
set nav_emerg_landing_speed = 500
set nav_min_rth_distance = 500
set nav_rth_climb_first = OFF
set nav_rth_climb_ignore_emerg = OFF
set nav_rth_tail_first = OFF
set nav_rth_allow_landing = FS_ONLY
set nav_rth_alt_mode = AT_LEAST
set nav_rth_abort_threshold = 50000
set nav_rth_altitude = 14000
set nav_mc_bank_angle = 30
set nav_mc_hover_thr = 1500
set nav_mc_auto_disarm_delay = 2000
set nav_fw_cruise_thr = 1650
set nav_fw_min_thr = 1200
set nav_fw_max_thr = 1995
set nav_fw_bank_angle = 35
set nav_fw_climb_angle = 35
set nav_fw_dive_angle = 30
set nav_fw_pitch2thr = 10
set nav_fw_loiter_radius = 2500
set nav_fw_land_dive_angle = 2
set nav_fw_launch_velocity = 300
set nav_fw_launch_accel = 1863
set nav_fw_launch_max_angle = 45
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1700
set nav_fw_launch_idle_thr = 1000
set nav_fw_launch_motor_delay = 500
set nav_fw_launch_spinup_time = 100
set nav_fw_launch_timeout = 5000
set nav_fw_launch_climb_angle = 18
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_latitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = METRIC
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set smartport_uart_unidir = OFF
set smartport_fuel_percent = OFF
set ibus_telemetry_type = 0
set ltm_update_rate = NORMAL
set ledstrip_visual_beeper = OFF
set osd_video_system = 2
set osd_row_shiftdown = 0
set osd_units = IMPERIAL
set osd_rssi_alarm = 59
set osd_cap_alarm = 0
set osd_time_alarm = 10
set osd_alt_alarm = 122
set osd_artificial_horizon_reverse_roll = OFF
set osd_crosshairs_style = DEFAULT
set osd_left_sidebar_scroll = NONE
set osd_right_sidebar_scroll = NONE
set osd_sidebar_scroll_arrows = OFF
set osd_main_voltage_pos = 2401
set osd_rssi_pos = 2102
set osd_flytimer_pos = 406
set osd_ontime_pos = 343
set osd_flymode_pos = 2440
set osd_throttle_pos = 369
set osd_vtx_channel_pos = 200
set osd_crosshairs_pos = 0
set osd_artificial_horizon_pos = 200
set osd_current_draw_pos = 97
set osd_mah_drawn_pos = 129
set osd_craft_name_pos = 84
set osd_gps_speed_pos = 2096
set osd_gps_sats_pos = 2105
set osd_gps_lon_pos = 2449
set osd_gps_lat_pos = 2417
set osd_home_dir_pos = 2094
set osd_home_dist_pos = 2087
set osd_altitude_pos = 2081
set osd_vario_pos = 183
set osd_vario_num_pos = 248
set osd_pid_roll_pos = 65
set osd_pid_pitch_pos = 97
set osd_pid_yaw_pos = 386
set osd_power_pos = 47
set osd_air_speed_pos = 163
set osd_ontime_flytime_pos = 2433
set osd_rtc_time_pos = 407
set osd_messages_pos = 2145
set osd_gps_hdop_pos = 2137
set osd_main_cell_voltage_pos = 2369
set osd_throttle_auto_thr_pos = 2408
set osd_heading_graph_pos = 106
set osd_efficiency_pos = 161
set i2c_speed = 400KHZ
set debug_mode = NONE
set acc_task_frequency = 500
set attitude_task_frequency = 250
set async_mode = NONE
set throttle_tilt_comp_str = 0
set input_filtering_mode = OFF
set mode_range_logic_operator = OR
set stats = OFF
set stats_total_time = 0
set stats_total_dist = 0
set tz_offset = 0

# profile
profile 1

set mc_p_pitch = 40
set mc_i_pitch = 30
set mc_d_pitch = 23
set mc_p_roll = 40
set mc_i_roll = 30
set mc_d_roll = 23
set mc_p_yaw = 85
set mc_i_yaw = 45
set mc_d_yaw = 0
set mc_p_level = 20
set mc_i_level = 15
set mc_d_level = 75
set fw_p_pitch = 6
set fw_i_pitch = 14
set fw_ff_pitch = 65
set fw_p_roll = 3
set fw_i_roll = 6
set fw_ff_roll = 28
set fw_p_yaw = 6
set fw_i_yaw = 10
set fw_ff_yaw = 60
set fw_p_level = 20
set fw_i_level = 5
set fw_d_level = 75
set max_angle_inclination_rll = 300
set max_angle_inclination_pit = 300
set dterm_lpf_hz = 40
set yaw_lpf_hz = 30
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 165
set fw_reference_airspeed =  1000.000
set fw_turn_assist_yaw_gain =  1.000
set dterm_notch_hz = 0
set dterm_notch_cutoff = 1
set pidsum_limit = 500
set yaw_p_limit = 300
set iterm_ignore_threshold = 200
set yaw_iterm_ignore_threshold = 50
set rate_accel_limit_roll_pitch = 0
set rate_accel_limit_yaw = 10000
set heading_hold_rate_limit = 90
set nav_mc_pos_z_p = 50
set nav_mc_pos_z_i = 0
set nav_mc_pos_z_d = 0
set nav_mc_vel_z_p = 100
set nav_mc_vel_z_i = 50
set nav_mc_vel_z_d = 10
set nav_mc_pos_xy_p = 65
set nav_mc_pos_xy_i = 120
set nav_mc_pos_xy_d = 10
set nav_mc_vel_xy_p = 180
set nav_mc_vel_xy_i = 15
set nav_mc_vel_xy_d = 100
set nav_fw_pos_z_p = 50
set nav_fw_pos_z_i = 0
set nav_fw_pos_z_d = 0
set nav_fw_pos_xy_p = 75
set nav_fw_pos_xy_i = 5
set nav_fw_pos_xy_d = 8
set rc_expo = 70
set rc_yaw_expo = 20
set thr_mid = 50
set thr_expo = 0
set roll_rate = 45
set pitch_rate = 18
set yaw_rate = 2
set tpa_rate = 35
set tpa_breakpoint = 1650`

**Comment by teckel12** [comment] 2017-10-28 14:15
If the Omnibus is a clone, it could be the clone OSD chip?  I've heard people with clone Omnibus FC having OSD issues.  If so, either turn off the max values or when they disappear you know you're over the limit.

**Comment by snowblind64** [comment] 2017-10-28 17:48
I bought this FC from RTFQ. Do they sell clones? I'll do a bit more testing today and try and get some DVR recording. It could be a hardware issue.

**Comment by teckel12** [comment] 2017-10-28 18:05
@snowblind64 That's not a clone then. Just a thought.

**Comment by snowblind64** [comment] 2017-10-29 03:14
Here is a link to DVR video of the issue: https://youtu.be/02xXpehBeQ4

See the video description for relevant times when issue occurs. Seems to affect anything that is meant to blink. I'm running the same board in a quad with Betaflight. Blinking of time and mAh consumed seem to work fine on the quad. Both are Omnibus F4 Pros from RTFQ. The one in the wing is an earlier version without the current sensor but with an SD card reader. It could be a hardware issue with my FC. I'll just turn off the alarms for now.

**Comment by digitalentity** [comment] 2017-10-29 03:18
@fiam FIY I've noticed that OSD is semi-transparent with latest code as if 7456 is only drawing in even or odd fields. In Eachine EV100 goggles this results in blinky OSD while in Headplay goggles it's perfectly fine.

**Comment by teckel12** [comment] 2017-10-29 04:12
Could it be the number of sensors on the same line? I remember some strange display issues when I had too many sensors turned on while testing. snowblind64 is displaying a lot in my opinion.

**Comment by snowblind64** [comment] 2017-10-29 21:02
I tried with a single item on screen. Same result. Looks like it could be something to do with the timing of the blinking and video frame rate, as it is not consistent. Sometimes the value being displayed stays solid, other times it disappears. I'm running NTSC video.

**Comment by fiam** [comment] 2017-10-30 08:14
@snowblind We can do some changes to the blink duty cycle and see what happens. I’ll prepare a custom build for you.

**Comment by fiam** [comment] 2017-10-30 10:36
@snowblind64 can you give this a try? Set some alarm to a very small value so you can easily bench test it and let me know what happens with the indicator.


[inav_1.8.0_OMNIBUSF4PRO.hex.zip](https://github.com/iNavFlight/inav/files/1426837/inav_1.8.0_OMNIBUSF4PRO.hex.zip)

**Comment by snowblind64** [comment] 2017-10-30 17:19
@fiam I'll give it a try tonight when I get home and report back.

**Comment by snowblind64** [comment] 2017-10-31 04:03
I flashed the hex. The entire OSD overlay turns grey obscuring nearly the entire view. Text is still visible over the greyed out screen but alarms are not blinking (I set the RSSI alarm to a high value so it would be triggered).

**Comment by digitalentity** [comment] 2017-11-01 04:55
Moving to 1.9. Will be a "known bug" in 1.8

**Comment by fiam** [comment] 2017-11-01 13:14
@snowblind64 I've just added support for software based blinking at the display level, so it can be used to perform blinking when the hardware support for it is not present or it's not working correctly. I've pushed the code to the `agh_sw_blink` branch, but I'm also attaching an hex to test to this post.

After flashing with it, you need to go into the CLI and type:

```
set display_force_sw_blink=ON
save
```

I've made the SW based implementation use a 1sec on/sec off cycle for now, to make it more evident when the SW implementation is being used. Please, give it a try and let us know how it works for you.

[inav_1.8.1_OMNIBUSF4PRO.hex.zip](https://github.com/iNavFlight/inav/files/1434211/inav_1.8.1_OMNIBUSF4PRO.hex.zip)

**Comment by snowblind64** [comment] 2017-11-02 04:27
Looks like that did it. Software blink works correctly. Thank you!

**Comment by fiam** [comment] 2017-11-02 08:13
Reopening since we haven’t pushed a fix to development yet

**Comment by teckel12** [comment] 2017-11-02 14:02
@fiam Is there a performance reason we can't make the software blink the default?  I'm sure it's *slightly* less performant, but it sounds like we could have problems with different hardware using the hardware blink.  It seems like this could avoid a lot of frustration and issues, unless the software blink is a large performance hit.

**Comment by fiam** [comment] 2017-11-02 17:07
@teckel12 Performance is a bit worse, specially because we can't use DMA to write to the MAX7456 in most boards and SW blink increases the number of writes significantly when an indicator is blinking. HW is definitely more desirable as long as the HW supports it. Depending on the feedback we get from users with 1.8, which uses HW blink with no SW blink option, we'll decide which one we'll use by default. If only a small amount of users are experiencing problems, I'd keep HW as the default.

**Comment by teckel12** [comment] 2017-11-02 18:18
@fiam Sounds like a plan.

**Comment by teckel12** [comment] 2017-11-09 15:29
@fiam I can confirm that with development build 1.8.0 values would go invisible instead of flashing. With release 1.8.0, the values disappear instead of flashing.

Was `display_force_sw_blink` added to 1.8.0 or is it only in the 1.8.1 build you posted here? It seems like a software option should at least be an option as the problem still exists.

**Comment by fiam** [comment] 2017-11-09 18:02
@teckel12 it was merged after 1.8, so it will be in the next release. Not sure about its default value yet.

**Comment by teckel12** [comment] 2017-11-10 02:06
I'll merge it into my local build. I have a fairly common setup, so I have to imagine many others have this problem. Glad you've already created a fix for it! Thanks.

**Comment by teckel12** [comment] 2017-11-10 02:09
Oh, I'll report back after I try your branch so we can close this.

**Comment by digitalentity** [comment] 2018-02-25 12:43
@teckel12 I'm going to close this

**Closed as completed by digitalentity** 2018-02-25 12:43 UTC
Labels: Bugfix, Feedback required
