### ISSUE TITLE
INAV 6.0.0 and Matek 405TE Mar 22 2023 with Jeti Receiver

### ISSUE THREAD

**Issue by ghost** [iNavFlight/inav#8923] opened 2023-03-29 08:54 UTC
Strange behaviour with INAV 6.0.0 and Matek 405TE Mar 22 2023 with Jeti Receiver

Pulling ROLL function for longer time (f.e. 2sec) the Roll Servos have very long delay to return back to neutral postion.
Pulling Roll function shortly everything is ok 

Some with elevator servo

Also RTH Mode is missing 

## Steps to Reproduce

1.
2.
3.
4.

## Additional context

---

- FC Board name and vendor:
- INAV version string:

**Comment by boomerschnecke** [comment] 2023-03-29 12:12
The behaviour depends on throttle position ! Only visible at full throttle

**Comment by RoadyFPV** [comment] 2023-03-31 15:42
Servos freeze compiled with ggc10 **and** with gcc9....
The issue does not seem to be related to this: https://github.com/iNavFlight/inav/issues/8899

**Comment by boomerschnecke** [comment] 2023-03-31 19:10
I am actually using SBus. So not connected to JetiEX-Bus issues !

**Comment by RobinatiNav** [comment] 2023-04-01 10:36
Well, I believe the ideal solution from iNav comunity view is to use FrSky. Forget about solving Jeti connected issues.....  ;)

**Comment by RoadyFPV** [comment] 2023-04-02 12:12
I flashed INAV5.1, the problem is there too.
I think thats not a JETI issue and should be renamed...

**Comment by RoadyFPV** [comment] 2023-04-02 12:16
I have found why the servos freeze...
u enter accidentally by stick wiggeling the OSD menu and the servos freeze until u leave it.

**Comment by boomerschnecke** [comment] 2023-04-02 12:42
Thanks for information.
Could you please explain how to enter this OSD menue mode by sticks activation in order to avoid it? Where is this procedure discribed? How to make a workaroud ?

**Comment by RoadyFPV** [comment] 2023-04-02 12:44
https://www.mrd-rc.com/tutorials-tools-and-testing/inav-flight/inav-stick-commands-for-all-transmitter-modes/

**Comment by boomerschnecke** [comment] 2023-04-02 12:56
Thank you. Didn´t know that, but is this only to be activated if unarmed? Otherwise if this could be activated all the time this would be a big problem?

**Comment by RoadyFPV** [comment] 2023-04-02 13:02
You should not be able to access the menu when armed.

**Comment by RoadyFPV** [comment] 2023-04-02 16:39
u can close the issue?

**Closed as completed** 2023-04-02 17:46 UTC
