### ISSUE TITLE
3.0 RC1 Blackbox log records home location as 0,0

### ISSUE THREAD

**Issue by OlivierC-FR** [iNavFlight/inav#7013] opened 2021-05-23 08:48 UTC
Distance to aircraft is wrong by few millions of meters, azimuth stays at 7 for the whole flight, and mah/km is some seemingly random values. After takeoff, mah/km is back to normal, but the 2 others stays very wrong for the whole flight.

[LOG10005.01.csv](https://github.com/iNavFlight/inav/files/6527784/LOG10005.01.csv)

![Capture d’écran 2021-05-23 104453](https://user-images.githubusercontent.com/25566932/119254013-3f926c00-bbb4-11eb-9a04-e1a310a927a7.jpg)

**Comment by stronnag** [comment] 2021-05-23 09:37
Official blackbox_decode does not show these derived values.
Some older RCs did, but the feature was removed for precisely the reasons shown in your image.

**Comment by stronnag** [comment] 2021-05-23 09:39
This is not a firmware issue,  see https://github.com/iNavFlight/blackbox-tools/pull/30 and linked PRs etc.

**Comment by OlivierC-FR** [comment] 2021-05-23 09:43
Ok thanks, will check blackbox version, can close the PR then.

**Comment by stronnag** [comment] 2021-05-23 10:04
Apologies, on examination of **BBL** it is a firmware issue, the home position is no longer being recorded on the log.

Possibly as a result of the new safehome processing (@tonyyng  any comment?)

**Comment by OlivierC-FR** [comment] 2021-05-23 10:51
Yep home point is definately at 0N 0E

![Capture d’écran 2021-05-23 125020](https://user-images.githubusercontent.com/25566932/119257464-9b192580-bbc5-11eb-94aa-7bd8d66e417a.jpg)

**Comment by stronnag** [comment] 2021-05-23 10:55
As is shown by the **stable release** `blackbox_decode`:

![Screenshot-20210523115506-576x373](https://user-images.githubusercontent.com/158229/119257586-d152a700-bbbd-11eb-827d-ae9b332abbea.png)

**Comment by tonyyng** [comment] 2021-05-23 11:01
> Possibly as a result of the new safehome processing (@tonyyng any comment?)

I don't use the blackbox logs with my planes since my flight controllers don't have enough memory to use it.  I tried looking at the code, but it is over my head.

@OlivierC-FR Do you have any safehomes defined?  Try a flight without any safehomes defined.  If the problem goes away, then the problem is likely related to safehomes.  If the problem still occurs, then it is likely not safehomes.

**Comment by stronnag** [comment] 2021-05-23 11:27
Don't think it's to do with safehome, let me look further.

**Comment by stronnag** [comment] 2021-05-23 12:05
On my quad, when armed, home is written to the BBL (it did have safehome enabled too)

@OlivierC-FR can you post your `diff` here please, let's try and see what ninja settings are causing this.

**Comment by OlivierC-FR** [comment] 2021-05-23 18:47
https://www.dropbox.com/s/m6u2sj76km7gsjy/Q5-F722SE.diff.txt?dl=0
https://www.dropbox.com/s/epd20sutrbc177i/Q5-F722SE.dump.txt?dl=0
No safehomes.

**Comment by stronnag** [comment] 2021-05-23 21:10
Thanks. So far I'm somewhat stumped on this. Works fine here on one quad regardless of safehome.

**Comment by wx4cb** [comment] 2021-05-23 21:30
here's a couple of log files from the other day, I don't have BB Explorer on this machine, but maybe it's useful to you.

No safe homes set

[LOG00014.TXT](https://github.com/iNavFlight/inav/files/6528949/LOG00014.TXT)
[LOG00007.TXT](https://github.com/iNavFlight/inav/files/6528950/LOG00007.TXT)

**Comment by stronnag** [comment] 2021-05-24 12:14
The mystery deepens. @OlivierC-FR 's is the only log I've seen where this happens. It's only the only log I've seen recently where BBL is on a switch rather than auto on ARM.

**Comment by stronnag** [comment] 2021-05-24 12:48
Sheesh !
```
set nav_extra_arming_safety = OFF
```
All bets are off. You armed without a GPS fix (and no home).

**Comment by OlivierC-FR** [comment] 2021-05-24 12:54
I went to the DVR and it does not tell much, I pressed the record button right after arming. It says 15 sats, but no way to be sure there was a GPS fix couple of seconds before. Anyway, in the case of no GPS fix, shouldn't it record as home the 1st correct GPS coordinates ? Or is it too late ? Like, if it hasn't happened at arming, no way to do it later I guess ?

![vlcsnap-2021-05-24-14h49m57s888](https://user-images.githubusercontent.com/25566932/119350439-a2146680-bc9f-11eb-809a-dd8ebe35181b.png)

**Comment by stronnag** [comment] 2021-05-24 12:58
> yway, in the case of no GPS fix, shouldn't it record as home the 1st correct GPS coordinates ? Or is it too late ? Like, if it hasn't happened at arming, no way to do it later I guess ?

You'd have hoped so. But it appears not, I may look a bit deeper, but this is no longer an "oh sh*t" issue for 3.0 IMO.

**Comment by OlivierC-FR** [comment] 2021-05-24 12:59
Generally speaking I do not take-off without a GPS fix, but in this particular case maybe I didn't wait for the fix, I don't recall. What's for sure I had zero plans to fly further away that few hundreds of meters. So let's say its probable the lack of GPS fix at arming caused that.

**Comment by OlivierC-FR** [comment] 2021-05-24 13:06
And what about this one ? : https://github.com/iNavFlight/inav/issues/6999
Incorrect mah ? Could it be somehow related ?
This one I for sure did not throw a plane without a proper GPS fix.
100%

**Comment by stronnag** [comment] 2021-05-26 20:48
The code is quite clear; home is only set when (a) there is an adequate GPS fix and (b) the craft is not armed.
The blackbox behaviour is entirely consistent in this case.
So let's close this.

**Closed as completed by stronnag** 2021-05-26 20:48 UTC
