### ISSUE TITLE
Telemetry via VTX Audiochannel

### ISSUE THREAD

**Issue by alfawhaaat** [iNavFlight/inav#2976] opened 2018-03-27 08:25 UTC
Came across this by doing researches for a tracker.
The LTM Protocoll at baud 1200 can be converted to AFSK using a AFSK Modem and send via VTX Audiochannel to the Groundstation transmitting GPS Data and other. (like ezuhf tracker telemetry)
AFSK Modem can be replaced by a Software Modem, there are countless gits you could get the code from, for example minimodem.
It doesn't seem to be a big effort, would this be possible in general, maybe using an motor output converting Serial to Analog Data?

**Comment by krzysztofmatula** [comment] 2018-03-28 07:02
See also: #2221

**Comment by fiam** [comment] 2018-04-04 11:09
Duplicate of #2221. Please, search before posting.

**Closed as completed by fiam** 2018-04-04 11:09 UTC
