### ISSUE TITLE
Issue with position of aircraft after about 1h and 30m

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav#1241] opened 2017-02-06 19:09 UTC
Board: Spracingf3mini
Diff and full dump: http://pastebin.com/H5AJBjyc
Video of issue: https://www.youtube.com/watch?v=ZuonAJwootE

reboot of FC fixes the issue, tried leaving it on for 24h and then disconnect and reconnect, same issue appeared after 1hour+, so it can`t be temperatur related.

Screenshot of sensor tab, with special build from @digitalentity 

![sensortab1](https://cloud.githubusercontent.com/assets/5670710/22662111/244e4930-eca8-11e6-9335-2109b84d15ce.png)
![sensortab2](https://cloud.githubusercontent.com/assets/5670710/22662112/244e74aa-eca8-11e6-912f-a84f7a618a54.png)

**Comment by oleost** [comment] 2017-02-06 19:12
Picture of sensor tab after when rebooted:

![image](https://cloud.githubusercontent.com/assets/5670710/22662198/77903ab8-eca8-11e6-9f0f-cc0d105efc2d.png)

![image](https://cloud.githubusercontent.com/assets/5670710/22662216/85846e8c-eca8-11e6-86ca-80921f99cfd0.png)

**Comment by digitalentity** [comment] 2017-02-06 23:11
This is a show-stopper for 1.6.

>dT jumps from positive to negative out of nowhere, one readout gets completely screwed and whole output is wrong
>happened after 1:15 more less
>so definetly it is connected with timer overflow

I confirmed the issue, it indeed looks like it's timer overflow. Possibly we forgot to convert to timeUs_t somewhere.

**Comment by digitalentity** [comment] 2017-02-07 00:14
Confirmed - issue happens when timer rolls over 2^32.

**Comment by digitalentity** [comment] 2017-02-07 02:33
Nailed it.

Root cause is `micros()` returning gibberish when millisecond counter ticks over 1h15min (4294967 ms since boot).

In `micros()` we have this code:
`(ms * 1000) + (usTicks * 1000 - cycle_cnt) / usTicks`

While it looks ok, this part `(ms * 1000)` is yielding 32-bit result while is only converted to `timeUs_t` later when doing addition.

Adding explicit typecast fixed the isse:
`((timeUs_t)ms * 1000LL) + (usTicks * 1000LL - (timeUs_t)cycle_cnt) / usTicks`

PR pending

**Comment by digitalentity** [comment] 2017-02-07 03:21
https://github.com/iNavFlight/inav/pull/1243

**Comment by martinbudden** [comment] 2017-02-07 10:15
I've added test code to check this. Unfortunately the test code passes even in the old version - compiler differences I presume. Still the test code might pick up a future error. See PR https://github.com/iNavFlight/inav/pull/1244

**Comment by digitalentity** [comment] 2017-02-07 10:38
@martinbudden thanks. I presume different compilers do type conversion differently - `cc` may cast everything to final type and then do the math. Apparently `gcc-arm-none-eabi` does type-conversion differently.

**Comment by digitalentity** [comment] 2017-02-07 12:56
Closing. #1243 nailed it.

**Closed as completed by digitalentity** 2017-02-07 12:56 UTC
Labels: Bugfix
