### ISSUE TITLE
DJI OSD Distance to home missing leading zero after decimal point 

### ISSUE THREAD

**Issue by roteron1** [iNavFlight/inav#7857] opened 2022-02-25 21:35 UTC
Whenever a new full km is reached, there is a missing leading zero after the decimal, i.e. 1.01km displays as 1. 1km. This repeats for every new km. There appears to be a space instead of a zero.

**Comment by Scavanger** [comment] 2022-02-27 23:01
This is not a bug in iNav. iNav only provides the pure number, the formatting is done in the DJI glasses. This must be fixed in the DJI firmware.

**Comment by DzikuVx** [comment] 2022-02-28 07:43
Just like @Scavanger said, this is DJI OSD bug, INAV is only providing value, not formatting

**Closed as completed by DzikuVx** 2022-02-28 07:43 UTC
