### ISSUE TITLE
Naze32, no sound at all.

### ISSUE THREAD

**Issue by makkuzu** [iNavFlight/inav#3820] opened 2018-08-29 11:54 UTC
I have been using betaflight and cleanflight, after I got my first nz gps I decided to use INAV, I installed the INAV firmware 1.7.3 Naze on my FC. After that, I have been getting no sound on my buzzer at all. With celanflight and betaflight I got no problem with my buzzer. 
Any help will be appraciated, thanks.

**Comment by makkuzu** [comment] 2018-08-29 14:30
Downgrading firmware from 1.7.3 to 1.7.2 solves beeper problem.

**Comment by shellixyz** [comment] 2018-08-29 19:55
Duplicate of #2330 and #2864

**Closed as completed** 2018-08-30 09:56 UTC
