### ISSUE TITLE
Waypoints doesn't work on Omnibus F4 Pro

### ISSUE THREAD

**Issue by compuatic** [iNavFlight/inav#2400] opened 2017-10-24 16:00 UTC
My experience trying to get waypoints to work with iNAV 1.7.2, 1.7.3, 1.8RC1

*excerpt below from my RC groups post*

1. iNAV configurator doesn't support any waypoint entry, even rudimentary via command line or other.
2. I went to mobile flight in hopes of making it work and discovered that you need a BLE module to make it work on iOS which I got. The App itself works great and uploads the waypoints but something is broken between it and iNAV since the controller wouldn't recognize and/or initiate the mission.
3. As a result of going to a BLE module, iNAV config no longer connects wirelessly since it needs a virtual com port which BLE doesn't provide.
4. I then tried EZ-GUI which only works on an Android phone. Same result as MobileFlight. Everything seems to work but mission doesn't work in iNAV.
5. All my settings were shared here. No issue found.
6. Blackbox shared, nothing found on 1.7.3
7. Recommendation to try 1.8RC1 and blackbox shows that iNAV doesn't recognize the mission which is definitely present in the flash and can be ready back by both Apps. otherwise 1.8RC1 seems to work well btw so well done there.

The last option now is to compile MWP and run it on a linux box to try yet one other thing. I have no other reason to setup a linux machine and this seems like way too much hassle so I'm stopping here. Not going to try yet another piece of software on yet a fourth operating system.

This is not a complaint to you or any particular person. It is just sharing my personal experience with the situation. I realize that this is Open Source and that users have to pretty much live with what they get, and for that I thank the developers for their hard work and all the other great features that work well. I have however made the conclusion that for the time being, Waypoints Navigation has had minimal support and is currently not working, or barely working under very specific usage conditions for iNAV. At minimum, it certainly it user friendly and hasn't had the same level of focus or development. Even a simple way to setup via CLI would have been nice. This to me is the only thing keeping it behind the big boys (APM, Vector, etc). Keep up the good work but iNAV doesn't do waypoints for me for now.

**Comment by teckel12** [comment] 2017-10-24 17:05
It would seem to me that waypoints should be added via a transmitter switch.  But maybe I'm over-
simplifying it.

**Comment by fiam** [comment] 2017-10-24 17:12
I’m working on a desktop and eventually mobile app for waypoints. Once I have it working I plan to to make sure WP mode works fine and implement the missing WO types (there are like 5-6 types defined,  but only 2 are actually working).

**Comment by stronnag** [comment] 2017-10-24 17:14
WP works just fine; I fly them multiple times per week and have done since 2015-12-12 on a number of FCs.

**Comment by stronnag** [comment] 2017-10-24 17:21
Looks to me much more like an ezgui and / or MobileFlight issue to me.

**Comment by fiam** [comment] 2017-10-24 17:48
Just to be clear, I’m not saying that WP doesn’t work right now, just that I don’t have the right setup to test it at the moment. @stronnag uses WP regularly with his own software and it works fine for him,  so it’s very likely that the issue is not in inav but in the software used for setting the waypoints.

**Comment by stronnag** [comment] 2017-10-24 18:10
@fiam, looking forward to you implementing the missing WP types; mwp is ready.

Any for the records, ezgui works just fine too. If I upload a set of waypoints from ezgui, then disconnect ezgui and connect mwp (both BT/3DR), then in mwp (which has no mission loaded), I get:

![mission-ok](https://user-images.githubusercontent.com/158229/31959935-0fae5160-b8ee-11e7-9d6d-d8525d8dc5a4.jpg)

i.e the result of MSP.WP_GETINFO, the FC tells me that there are 15 waypoints and a confirmed, valid mission in FC memory (@compuatic, these are the values that are reported in the blackbox log in 1.8); 
mwp then automagically downloads, for visual confirmation (and I know why I can't arm), which is not surprising as I'm at home c. 600 from the field.

![mission-ok-2](https://user-images.githubusercontent.com/158229/31959998-4c9e0494-b8ee-11e7-98e3-e3e9dbeef2f1.jpg)

**So, mwp works, ezgui works**, the MobileFlight author has admitted that MobileFlight doesn't work with iNav at the moment; **there is no iNav issue here**.

**Comment by compuatic** [comment] 2017-10-24 18:30
@stronnag, EZgui upload and reads back just fine for me as well. The problem is switching into waypoints navigation during flight does absolutely nothing.

What mode are you in prior to arming? what controller are you using? could this be an omnibus F4PRO issue only?

**Comment by compuatic** [comment] 2017-10-24 18:36
And by the way mobile flight connected to inav just fine, it now won't connect to 1.8 only. This is separate from the waypoints issue.

**Comment by stronnag** [comment] 2017-10-24 18:37
You cannot prove that you have waypoints the the FC, in my case the result of MSP_WP_GETINFO demonstrates there are WP in the FC; your log showed there are 0 waypoints in the FC.

Mode prior to arm would be either acro or horizon. As WP demonstrably works for me on NAZE, SPRacingF3, SPRacingF3EVO, RMRC Dodo, OmnibusF3, Matek F405 AIO and Matek F405 OSD, I would be extremely suprised is it didn't work on another F4.

But that's irrelevant, your log showed there are no waypoints in the FC.

**Comment by stronnag** [comment] 2017-10-24 18:38
Apropros Mobile Flight, see https://www.rcgroups.com/forums/showpost.php?p=38492811&postcount=326

**Comment by compuatic** [comment] 2017-10-24 18:57
I will take a video showing uzgui downloading the mission file from the controller upon powerup with. O prior mission on ezgui. Hopefully that qualifies as proof of what I'm doing.

**Comment by stronnag** [comment] 2017-10-24 18:59
Do what you like, until your blackbox shows a valid mission you're wasting our time.

**Comment by digitalentity** [comment] 2017-10-25 01:29
Waypoint flight works for me. Please provide a blackbox log of a flight done in 1.8-RC2 where waypoint mission doesn't activate.

**Comment by compuatic** [comment] 2017-10-25 02:36
Here is a log from 1.8RC1
https://www.rcgroups.com/forums/showatt.php?attachmentid=10452190&d=1508733124

Stronnag says datalog confirms that iNAV sees no mission file even though ezgui confirms a valid mission is present via download off the controller. This is a plane not multirotor.

**Comment by digitalentity** [comment] 2017-10-25 02:48
Please note that disconnecting the power will erase mission from RAM. Flash may retain the previously saved mission, but it is not loaded back to RAM automatically.

You should upload the mission in the field and should not disconnect the flight battery after that.

**Comment by compuatic** [comment] 2017-10-25 02:59
Thank you for that info. I have noticed that the board will not arm if I upload a new mission at the field unless the power is cycled, this probably confirms what you are saying regarding the memory. The safety distance is set to the max of 6500 meters and the first waypoint is only a 100 meters or so away from home.

**Comment by compuatic** [comment] 2017-10-25 04:37
Konstantin,
   I got it working with ezgui. Your hints above was the ticket. The trick was to first load and save into non volatile memory, then load into ram without power cycling. Waypoints now work. Powercycling disables it again. Non intuitive but I am relieved.

Any reason why iNAV can not auto load from flash? Ability to do manually or via a mode would be much more convenient.

**Comment by digitalentity** [comment] 2017-10-25 04:44
You may have an old mission in non-volatile storage. Auto-loading mission may prevent you from flying. 
Actually you don't have to save mission to non-volatile memory at all. EzGUI will upload it to RAM and you can execute mission normally.

Alternatively, you can plan mission at home, upload, save to non-volatile memory, power off. Then you go to the field, power up the machine, load the mission using stick combo and fly it without having to use EzGUI:
![image](https://user-images.githubusercontent.com/11059099/31980889-ee70bd3a-b992-11e7-95ed-ae26dbaaf917.png)

**Comment by DzikuVx** [comment] 2017-11-17 09:15
Since ticket got into stuck phase, I'm closing it. If any new data appears, fee free to reopen

**Closed as completed by DzikuVx** 2017-11-17 09:15 UTC
