### ISSUE TITLE
New Target SP RACING H7 ZERO

### ISSUE THREAD

**Issue by rgp1942** [iNavFlight/inav#5638] opened 2020-04-27 19:53 UTC
Please add new flight controller SP RACING H7 ZERO, which contains the new BMP388 barometer, which is twice as accurate as the BMP280 barometer.
http://seriouslypro.com/spracingh7zero

This provides the best solution yet for effective altitude hold.

I'm sure SP RACING will provide all the needed information to create a new target.
https://shop.seriouslypro.com/contact/

**Comment by digitalentity** [comment] 2020-04-28 06:38
Duplicate of #5212

**Closed as completed by digitalentity** 2020-04-28 06:38 UTC

**Comment by hydra** [comment] 2020-05-01 15:13
@digitalentity I can help with the target definition once processor support is underway.

@rgp1942 I fully agree that the SPRacingH7ZERO makes for a GREAT iNAV board.
