### ISSUE TITLE
servos moves with throtle

### ISSUE THREAD

**Issue by ksakwa** [iNavFlight/inav#2072] opened 2017-09-03 22:26 UTC
HI. I have a big problem.
In my CC3d Atom with Inav 1.7.2 (also betaflight), when stabilisation is ON and i  increase the throttle, the servos (ail and elev move to the right or left). When TH is 0, the servo returns to neutral. i havent any mix on radio or FC. can you help me ?
link to youtube:
https://youtu.be/GSfwF1dDH7E

**Comment by digitalentity** [comment] 2017-09-04 13:08
Please provide more details about your setup. CLI `dump` is a must to troubleshoot.

**Comment by cabinw** [comment] 2017-09-06 17:12
@ksakwa Your fc might not be leveled and inav is work hard to let your plane be leveled but it didn't work so the servo kept moving. I guess

**Comment by fiam** [comment] 2017-09-06 20:41
If you haven't enabled AIR mode, it seems to be working as intended. The FC will not try to level itself when THR is zero. As soon as you apply THR, the FC starts applying stabilisation because you have it tilted on the table. Have you enabled AIR mode?

**Comment by DzikuVx** [comment] 2017-09-26 11:12
Since no new data appeared, closing this one. In case of new data please reopen

**Closed as completed by DzikuVx** 2017-09-26 11:12 UTC
Labels: Feedback required, Support
