### ISSUE TITLE
BLHeli_32 ESC telemetry

### ISSUE THREAD

**Issue by xermalk** [iNavFlight/inav#3629] opened 2018-07-19 22:51 UTC
Reopening this feature request. https://github.com/iNavFlight/inav/issues/2710

ESC telemetry (CURR/RPM/TEMP) would be a **_massive_** benefit for wing wiring and and allow for extra warnings if esc is to hot or the motor rpm differs to match from the throttle signal.

Its also one more reason to use the new BLHELI32 60-70-80A escs in planes.  Some of them are as light as 4.5g ! vs a regular plane esc are usualy 60-80g for similar specs.

**Comment by digitalentity** [comment] 2018-07-20 16:40
Duplicate of #2710. Reopened.

**Closed as completed by digitalentity** 2018-07-20 16:40 UTC

**Comment by putimir** [comment] 2019-08-14 14:14
Hey @digitalentity, what is this: 
![image](https://user-images.githubusercontent.com/33059362/63028181-9b43a780-beae-11e9-90d0-4173b494d173.png)
